import {encryptedText} from "./encrypted-text";
import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const applications = sqliteTable("applications", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  applicantName: encryptedText("applicant_name","applications.applicant_name").notNull(),
  applicantPhone: encryptedText("applicant_phone","applications.applicant_phone").notNull(),
  applicantBirth: encryptedText("applicant_birth","applications.applicant_birth").notNull(),
  applicantGender: text("applicant_gender").notNull(),
  careerYears: text("career_years").notNull(),
  qualification: text("qualification").notNull().default(""),
  preferredDate: text("preferred_date").notNull(),
  applicationNote: encryptedText("application_note","applications.application_note").notNull().default(""),
  providerCareType: text("provider_care_type").notNull().default("개인간병"),
  providerSchedule: text("provider_schedule").notNull().default("전일제(24시간)"),
  providerAvailableHours: text("provider_available_hours").notNull().default(""),
  providerRestTerms: text("provider_rest_terms").notNull().default("상호 협의"),
  providerFee: text("provider_fee").notNull().default(""),
  providerFeePeriod: text("provider_fee_period").notNull().default("1일"),
  providerServiceScope: text("provider_service_scope").notNull().default(""),
  providerContractNote: text("provider_contract_note").notNull().default(""),
  providerContractConsent: text("provider_contract_consent").notNull().default("미동의"),
  providerContractVersion: text("provider_contract_version").notNull().default("간병24 제공계약서 v1.0"),
  providerContractSignedAt: text("provider_contract_signed_at").notNull().default(""),
  caregiverHandwriting: encryptedText("caregiver_handwriting","applications.caregiver_handwriting").notNull().default(""),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const boardPosts = sqliteTable("board_posts", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  boardType: text("board_type").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  author: text("author").notNull().default("관리자"),
  attachments: text("attachments").notNull().default("[]"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const careRequests = sqliteTable("care_requests", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  requesterName: encryptedText("requester_name","care_requests.requester_name").notNull(),
  requesterPhone: encryptedText("requester_phone","care_requests.requester_phone").notNull(),
  patientName: encryptedText("patient_name","care_requests.patient_name").notNull(),
  patientGender: encryptedText("patient_gender","care_requests.patient_gender").notNull().default(""),
  patientBirthYear: encryptedText("patient_birth_year","care_requests.patient_birth_year").notNull().default(""),
  patientAge: encryptedText("patient_age","care_requests.patient_age").notNull().default(""),
  patientWeight: encryptedText("patient_weight","care_requests.patient_weight").notNull().default(""),
  diagnosis: encryptedText("diagnosis","care_requests.diagnosis").notNull().default(""),
  patientCondition: encryptedText("patient_condition","care_requests.patient_condition").notNull().default(""),
  precautions: encryptedText("precautions","care_requests.precautions").notNull().default(""),
  specialNotes: encryptedText("special_notes","care_requests.special_notes").notNull().default(""),
  publicConsent: text("public_consent").notNull().default("미동의"),
  building: text("building").notNull(),
  floorName: text("floor_name").notNull().default(""),
  ward: text("ward").notNull(),
  room: encryptedText("room","care_requests.room").notNull().default(""),
  careType: text("care_type").notNull(),
  startDate: text("start_date").notNull(),
  requestNote: encryptedText("request_note","care_requests.request_note").notNull().default(""),
  serviceSchedule: text("service_schedule").notNull().default("전일제(24시간)"),
  serviceStartTime: text("service_start_time").notNull().default(""),
  serviceEndTime: text("service_end_time").notNull().default(""),
  restTime: text("rest_time").notNull().default("상호 협의"),
  holidayTerms: text("holiday_terms").notNull().default("상호 협의"),
  careFee: text("care_fee").notNull().default(""),
  feePeriod: text("fee_period").notNull().default("1일"),
  paymentMethod: text("payment_method").notNull().default("계좌이체"),
  paymentDue: text("payment_due").notNull().default(""),
  serviceScope: text("service_scope").notNull().default(""),
  cancellationTerms: text("cancellation_terms").notNull().default(""),
  contractNote: encryptedText("contract_note","care_requests.contract_note").notNull().default(""),
  requesterSignature: encryptedText("requester_signature","care_requests.requester_signature").notNull().default(""),
  contractConsent: text("contract_consent").notNull().default("미동의"),
  contractVersion: text("contract_version").notNull().default("간병24 의뢰계약서 v1.0"),
  contractSignedAt: text("contract_signed_at").notNull().default(""),
  desiredGender: text("desired_gender").notNull().default("무관"),
  desiredNationality: text("desired_nationality").notNull().default("무관"),
  desiredExpertise: text("desired_expertise").notNull().default("무관"),
  desiredAge: text("desired_age").notNull().default("무관"),
  desiredPersonality: text("desired_personality").notNull().default("무관"),
  desiredOther: text("desired_other").notNull().default(""),
  status: text("status").notNull().default("requesting"),
  caregiverId: integer("caregiver_id"),
  caregiverName: encryptedText("caregiver_name","care_requests.caregiver_name").notNull().default(""),
  caregiverProfile: encryptedText("caregiver_profile","care_requests.caregiver_profile").notNull().default(""),
  matchedAt: text("matched_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const documentBundles = sqliteTable("document_bundles", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  caregiverName: encryptedText("caregiver_name","document_bundles.caregiver_name").notNull(),
  caregiverPhone: encryptedText("caregiver_phone","document_bundles.caregiver_phone").notNull(),
  bankName: text("bank_name").notNull().default(""),
  accountNumber: encryptedText("account_number","document_bundles.account_number").notNull().default(""),
  accountHolder: encryptedText("account_holder","document_bundles.account_holder").notNull().default(""),
  documentStatuses: text("document_statuses").notNull(),
  attachments: encryptedText("attachments","document_bundles.attachments").notNull().default("[]"),
  criminalRequestData: encryptedText("criminal_request_data","document_bundles.criminal_request_data").notNull().default("{}"),
  criminalReviewer: encryptedText("criminal_reviewer","document_bundles.criminal_reviewer").notNull().default(""),
  criminalReviewedAt: text("criminal_reviewed_at").notNull().default(""),
  criminalResult: encryptedText("criminal_result","document_bundles.criminal_result").notNull().default("확인 대기"),
  evaluation: encryptedText("evaluation","document_bundles.evaluation").notNull(),
  decision: encryptedText("decision","document_bundles.decision").notNull(),
  reviewer: encryptedText("reviewer","document_bundles.reviewer").notNull(),
  reviewedAt: text("reviewed_at").notNull(),
  note: encryptedText("note","document_bundles.note").notNull().default(""),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  confirmedAt: text("confirmed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const privacyConsents = sqliteTable("privacy_consents", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: encryptedText("name","privacy_consents.name").notNull(),
  phone: encryptedText("phone","privacy_consents.phone").notNull(),
  birthDate: encryptedText("birth_date","privacy_consents.birth_date").notNull(),
  address: encryptedText("address","privacy_consents.address").notNull(),
  retentionPeriod: text("retention_period").notNull(),
  useConsent: text("use_consent").notNull(),
  shareConsent: text("share_consent").notNull(),
  signatureName: encryptedText("signature_name","privacy_consents.signature_name").notNull(),
  signedAt: text("signed_at").notNull(),
  caregiverHandwriting: encryptedText("caregiver_handwriting","privacy_consents.caregiver_handwriting").notNull().default(""),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  confirmedAt: text("confirmed_at"),
  completedAt: text("completed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const careContracts = sqliteTable("care_contracts", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractType: text("contract_type").notNull(),
  employerName: encryptedText("employer_name","care_contracts.employer_name").notNull(),
  employerPhone: encryptedText("employer_phone","care_contracts.employer_phone").notNull(),
  employerAddress: encryptedText("employer_address","care_contracts.employer_address").notNull().default(""),
  caregiverName: encryptedText("caregiver_name","care_contracts.caregiver_name").notNull(),
  caregiverPhone: encryptedText("caregiver_phone","care_contracts.caregiver_phone").notNull(),
  caregiverAddress: encryptedText("caregiver_address","care_contracts.caregiver_address").notNull().default(""),
  caregiverHandwriting: encryptedText("caregiver_handwriting","care_contracts.caregiver_handwriting").notNull().default(""),
  patientName: encryptedText("patient_name","care_contracts.patient_name").notNull(),
  workplace: text("workplace").notNull(),
  workStart: text("work_start").notNull(),
  workEnd: text("work_end").notNull(),
  workHours: text("work_hours").notNull(),
  salaryAmount: text("salary_amount").notNull().default(""),
  salaryPeriod: text("salary_period").notNull(),
  fullTimeSalary: text("full_time_salary").notNull().default(""),
  twoShiftSalary: text("two_shift_salary").notNull().default(""),
  threeShiftSalary: text("three_shift_salary").notNull().default(""),
  private24Salary: text("private_24_salary").notNull().default(""),
  privateDay12Salary: text("private_day_12_salary").notNull().default(""),
  privateNight12Salary: text("private_night_12_salary").notNull().default(""),
  privateHourlySalary: text("private_hourly_salary").notNull().default(""),
  payDate: text("pay_date").notNull(),
  bankName: text("bank_name").notNull().default(""),
  bankAccount: encryptedText("bank_account","care_contracts.bank_account").notNull().default(""),
  bankHolder: encryptedText("bank_holder","care_contracts.bank_holder").notNull().default(""),
  socialInsurance: text("social_insurance").notNull().default("미가입"),
  retirementPension: text("retirement_pension").notNull().default("미가입"),
  benefitNote: text("benefit_note").notNull().default(""),
  topCount: text("top_count").notNull().default("0"),
  bottomCount: text("bottom_count").notNull().default("0"),
  apronCount: text("apron_count").notNull().default("0"),
  shoesCount: text("shoes_count").notNull().default("0"),
  nameTagCount: text("name_tag_count").notNull().default("0"),
  duties: text("duties").notNull(),
  specialTerms: encryptedText("special_terms","care_contracts.special_terms").notNull().default(""),
  employerSignature: encryptedText("employer_signature","care_contracts.employer_signature").notNull(),
  caregiverSignature: encryptedText("caregiver_signature","care_contracts.caregiver_signature").notNull(),
  signedAt: text("signed_at").notNull(),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  confirmedAt: text("confirmed_at"),
  completedAt: text("completed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const submissions = sqliteTable("submissions", {
  ownerUserId: text("owner_user_id"),
  hospitalId: text("hospital_id"),
  id: integer("id").primaryKey({ autoIncrement: true }),
  applicantName: encryptedText("applicant_name","submissions.applicant_name").notNull().default(""),
  applicantPhone: encryptedText("applicant_phone","submissions.applicant_phone").notNull().default(""),
  applicantBirth: encryptedText("applicant_birth","submissions.applicant_birth").notNull().default(""),
  applicantGender: text("applicant_gender").notNull().default(""),
  careerYears: text("career_years").notNull().default(""),
  qualification: text("qualification").notNull().default(""),
  preferredDate: text("preferred_date").notNull().default(""),
  applicationNote: encryptedText("application_note","submissions.application_note").notNull().default(""),
  caregiverName: encryptedText("caregiver_name","submissions.caregiver_name").notNull(),
  caregiverOrg: text("caregiver_org").notNull(),
  caregiverHandwriting: encryptedText("caregiver_handwriting","submissions.caregiver_handwriting").notNull().default(""),
  ward: text("ward").notNull(),
  room: text("room").notNull(),
  patientName: encryptedText("patient_name","submissions.patient_name").notNull(),
  workStart: text("work_start").notNull(),
  workEnd: text("work_end").notNull(),
  contractType: text("contract_type").notNull().default("개인간병"),
  feeType: text("fee_type").notNull(),
  feeAmount: text("fee_amount").notNull(),
  feePeriod: text("fee_period").notNull().default("1일"),
  commonFullTimeFee: text("common_full_time_fee").notNull().default(""),
  commonTwoShiftFee: text("common_two_shift_fee").notNull().default(""),
  commonThreeShiftFee: text("common_three_shift_fee").notNull().default(""),
  personalFee: text("personal_fee").notNull().default(""),
  feeNote: encryptedText("fee_note","submissions.fee_note").notNull().default(""),
  satisfaction: encryptedText("satisfaction","submissions.satisfaction").notNull(),
  duties: encryptedText("duties","submissions.duties").notNull(),
  rules: encryptedText("rules","submissions.rules").notNull(),
  overall: encryptedText("overall","submissions.overall").notNull(),
  headNurse: encryptedText("head_nurse","submissions.head_nurse").notNull(),
  confirmedAt: text("confirmed_at").notNull(),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  completedAt: text("completed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
