import {withActor,scope,scopedId,ownership,workflowGuard,type Actor} from "../../../lib/auth";
import{desc,eq,sql}from"drizzle-orm";import{getDb}from"../../../db";import{privacyConsents}from"../../../db/schema";
const required=["name","phone","birthDate","address","retentionPeriod","useConsent","shareConsent","signatureName","signedAt","signatureAgree"] as const;
function valid(b:Record<string,any>){return required.every(k=>String(b[k]||"").trim())}
function values(b:Record<string,any>){const a=b.action||"save";return{name:b.name,phone:b.phone,birthDate:b.birthDate,address:b.address,retentionPeriod:b.retentionPeriod,useConsent:b.useConsent,shareConsent:b.shareConsent,signatureName:b.signatureName,signedAt:b.signedAt,caregiverHandwriting:b.caregiverHandwriting||"",status:a==="complete"?"completed":a==="confirm"?"confirmed":a==="send"?"sent":"saved",sentTargets:a==="save"?"":"협회 · 간병24",confirmedAt:a==="confirm"||a==="complete"?sql`CURRENT_TIMESTAMP`:null,completedAt:a==="complete"?sql`CURRENT_TIMESTAMP`:null}}
async function handleGET(req:Request, actor:Actor){try{return Response.json({consents:await getDb().select().from(privacyConsents).where(scope(privacyConsents,actor)).orderBy(desc(privacyConsents.id)).limit(100)})}catch{return Response.json({error:"개인정보 확인서 접수함을 불러올 수 없습니다."},{status:500})}}
async function handlePOST(req:Request, actor:Actor){try{const b=await req.json() as Record<string,any>;if(!valid(b))return Response.json({error:"필수 항목과 서명 동의를 모두 작성해주세요."},{status:400});const[x]=await getDb().insert(privacyConsents).values({...values(b),...ownership(actor)}).returning();return Response.json({consent:x},{status:201})}catch{return Response.json({error:"확인서 저장 중 문제가 발생했습니다."},{status:500})}}
async function handlePATCH(req:Request, actor:Actor){try{const b=await req.json() as Record<string,any>,id=Number(b.id);if(!id||!valid(b))return Response.json({error:"필수 항목과 서명 동의를 모두 작성해주세요."},{status:400});const[x]=await getDb().update(privacyConsents).set(values(b)).where(scopedId(privacyConsents,id,actor)).returning();return x?Response.json({consent:x}):Response.json({error:"확인서를 찾을 수 없습니다."},{status:404})}catch{return Response.json({error:"확인서 처리 중 문제가 발생했습니다."},{status:500})}}

export const GET=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handleGET(req,actor);});
export const POST=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePOST(req,actor);});
export const PATCH=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePATCH(req,actor);});
