import {withActor,scope,scopedId,ownership,workflowGuard,type Actor} from "../../../lib/auth";
import {privateBucket} from "../../../lib/private-storage";import{desc,eq,sql}from"drizzle-orm";import{getDb}from"../../../db";import{documentBundles}from"../../../db/schema";
const labels=["신분증 앞·뒤 복사본","자격증 사본","최종학교 졸업증명서","건강진단서","범죄경력 확인(담당자 전용)"];
function state(action:string){return{status:action==="confirm"?"confirmed":action==="send"?"sent":"saved",sentTargets:action==="save"?"":"협회 · 간병24",confirmedAt:action==="confirm"?sql`CURRENT_TIMESTAMP`:null}}
function allowed(file:File){return file.type.startsWith("image/")||file.type.startsWith("video/")||file.type==="application/pdf"}
async function parse(request:Request,existingAttachments="[]"){const f=await request.formData(),name=String(f.get("caregiverName")||"").trim(),phone=String(f.get("caregiverPhone")||"").trim(),bankName=String(f.get("bankName")||"").trim(),accountNumber=String(f.get("accountNumber")||"").trim(),accountHolder=String(f.get("accountHolder")||"").trim(),criminalReviewer=String(f.get("criminalReviewer")||"").trim(),criminalReviewedAt=String(f.get("criminalReviewedAt")||""),criminalResult=String(f.get("criminalResult")||"확인 대기"),evaluation=String(f.get("evaluation")||""),decision=String(f.get("decision")||""),reviewer=String(f.get("reviewer")||"").trim(),reviewedAt=String(f.get("reviewedAt")||""),action=String(f.get("action")||"save"),statuses=labels.map((label,i)=>({number:i+1,label,status:i===4?criminalResult:String(f.get(`status_${i}`)||"미제출")})),criminalRequestData=JSON.stringify(Object.fromEntries(["requesterName","requesterResidentNo","requesterOrg","requesterAddress","requesterPhone","subjectName","subjectResidentNo","employmentOrg","employmentAddress","employmentPhone","inquiryPurpose","occupation","requestDate","requesterSignature","adminInfoConsent","facilityHeadSignature"].map(k=>[k,String(f.get(k)||"")])));if(!name||!phone||!evaluation||!decision||!reviewer||!reviewedAt)throw Error("필수 항목을 모두 작성해주세요.");if(action==="confirm"&&(!criminalReviewer||!criminalReviewedAt||criminalResult==="확인 대기"))throw Error("확인 완료 전 담당자가 범죄경력 확인 결과를 작성해주세요.");
 let attachments:any[]=JSON.parse(existingAttachments);if(existingAttachments==="[]"){let total=0;const groups=[...labels.slice(0,4).map((label,i)=>({field:`files_${i}`,label,number:i+1})),{field:"bankFile",label:"본인 은행계좌 증빙",number:6}];for(const group of groups){for(const entry of f.getAll(group.field)){if(!(entry instanceof File)||!entry.size)continue;if(entry.size>20*1024*1024)throw Error(`${group.label} 파일은 20MB 이하만 첨부할 수 있습니다.`);if(!allowed(entry))throw Error("사진, 동영상 또는 PDF 파일만 첨부할 수 있습니다.");total+=entry.size;if(total>60*1024*1024)throw Error("전체 첨부파일은 60MB 이하만 저장할 수 있습니다.");const key=`caregiver-documents/${crypto.randomUUID()}`;await privateBucket.put(key,entry.stream(),{httpMetadata:{contentType:entry.type}});attachments.push({documentNumber:group.number,documentType:group.label,fileName:entry.name,mimeType:entry.type,size:entry.size,storageKey:key})}}}
 const hasBankFile=attachments.some(a=>a.documentNumber===6),hasBankText=!!(bankName&&accountNumber&&accountHolder);if(!hasBankFile&&!hasBankText)throw Error("은행명·계좌번호·예금주를 입력하거나 통장 사본을 첨부해주세요.");
 return{id:Number(f.get("id")||0),action,data:{caregiverName:name,caregiverPhone:phone,bankName,accountNumber,accountHolder,documentStatuses:JSON.stringify(statuses),attachments:JSON.stringify(attachments),criminalRequestData,criminalReviewer,criminalReviewedAt,criminalResult,evaluation,decision,reviewer,reviewedAt,note:String(f.get("note")||""),...state(action)}}}
async function handleGET(req:Request, actor:Actor){try{return Response.json({bundles:await getDb().select().from(documentBundles).where(scope(documentBundles,actor)).orderBy(desc(documentBundles.id)).limit(100)})}catch{return Response.json({error:"제출서류 접수함을 불러올 수 없습니다."},{status:500})}}
async function handlePOST(req:Request, actor:Actor){try{const{data}=await parse(req);if(actor.role==="caregiver")Object.assign(data,{criminalReviewer:"",criminalReviewedAt:"",criminalResult:"확인 대기",evaluation:"담당자 확인 대기",decision:"담당자 확인 대기",reviewer:"",reviewedAt:""});const[row]=await getDb().insert(documentBundles).values({...data,...ownership(actor)}).returning();return Response.json({bundle:row},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"서류 저장 중 문제가 발생했습니다."},{status:400})}}
async function handlePATCH(req:Request, actor:Actor){try{const probe=await req.clone().formData(),id=Number(probe.get("id")||0);if(!id)return Response.json({error:"서류번호가 없습니다."},{status:400});const[old]=await getDb().select().from(documentBundles).where(scopedId(documentBundles,id,actor)).limit(1);if(!old)return Response.json({error:"저장된 서류를 찾을 수 없습니다."},{status:404});const{data}=await parse(req,old.attachments);if(actor.role==="caregiver")Object.assign(data,{criminalReviewer:old.criminalReviewer,criminalReviewedAt:old.criminalReviewedAt,criminalResult:old.criminalResult,evaluation:old.evaluation,decision:old.decision,reviewer:old.reviewer,reviewedAt:old.reviewedAt});const[row]=await getDb().update(documentBundles).set(data).where(scopedId(documentBundles,id,actor)).returning();return Response.json({bundle:row})}catch(e){return Response.json({error:e instanceof Error?e.message:"서류 처리 중 문제가 발생했습니다."},{status:400})}}

export const GET=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handleGET(req,actor);});
export const POST=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePOST(req,actor);});
export const PATCH=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePATCH(req,actor);});
