"use client";
import {useEffect,useState} from 'react';
import RecordAssignment from './record-assignment';
type Hospital={id:string;name:string};type User={id:string;username:string;name:string;requested_role:string;requested_hospital:string;role:string;hospital_id:string|null;status:string};
export default function Admin(){const[users,setUsers]=useState<User[]>([]),[hospitals,setHospitals]=useState<Hospital[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/users',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setUsers(d.users);setHospitals(d.hospitals);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>,u?:User){e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));setBusy(true);setMessage('');try{const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(u?{...body,id:u.id}:{...body,action:'hospital'})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage('저장했습니다. 권한이 변경된 계정은 다시 로그인해야 합니다.');}catch(e){setMessage(e instanceof Error?e.message:'처리 실패');}finally{setBusy(false);}}
 return <main className="admin-page"><h1>가입 승인·소속 관리</h1><p>신청 내용과 실제 소속을 확인한 뒤 역할·병원을 지정해 승인하세요.</p><p role="status">{message}</p><form className="auth-card" onSubmit={e=>submit(e)}><h2>병원 등록</h2><label>병원 이름<input name="name" required maxLength={120}/></label><button disabled={busy}>병원 추가</button></form><RecordAssignment hospitals={hospitals} users={users}/><h2>가입 신청 및 계정</h2>{!users.length&&<p>표시할 계정이 없습니다.</p>}{users.map(u=><form key={u.id} className="auth-card account-row" onSubmit={e=>submit(e,u)}><h3>{u.name} · {u.username}</h3><p>신청: {u.requested_role==='hospital'?'병원 담당자':'간병인'} / {u.requested_hospital||'미지정'}</p><p>현재: {({pending:'승인 대기',active:'이용 중',rejected:'반려',suspended:'이용 정지'} as Record<string,string>)[u.status]}</p>{u.role!=='admin'&&<><label>승인 역할<select name="role" defaultValue={u.status==='pending'?u.requested_role:u.role}><option value="caregiver">간병인</option><option value="hospital">병원 담당자</option></select></label><label>확인된 소속 병원<select name="hospitalId" defaultValue={u.hospital_id||''}><option value="">병원을 선택하세요</option>{hospitals.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>처리<select name="status" defaultValue={u.status==='pending'?'active':u.status}><option value="active">승인 / 이용 허용</option><option value="rejected">가입 반려</option><option value="suspended">이용 정지</option></select></label><button disabled={busy}>확인 후 저장</button></>}</form>)}</main>;
}
