"use client";
import {useEffect,useRef,useState} from 'react';
type Bed={number:string;patient:string;caregiver:string};
type Room={id:string;room:string;version:number;capacity:number;toilet:string;beds:Record<string,Bed>};
export default function BedAssignments({building,ward,capacity,toilet,onLayout,hospitalName=""}:{hospitalName?:string;building:string;ward:string;capacity:number;toilet:string;onLayout:(capacity:number,toilet:string)=>void}){
 const [hospitals,setHospitals]=useState<{id:string;name:string}[]>([]),[hospital,setHospital]=useState(''),[rooms,setRooms]=useState<Room[]>([]),[selected,setSelected]=useState(''),[roomName,setRoomName]=useState('');
 const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[slot,setSlot]=useState(0),[saving,setSaving]=useState(false),[draft,setDraft]=useState<Bed>({number:'',patient:'',caregiver:''});
 const dialog=useRef<HTMLDialogElement>(null);
 const current=rooms.find(r=>r.id===selected);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setSelected('');setRooms([]);setRoomName('');setMessage('');fetch('/api/ward-assignments?'+new URLSearchParams({building,ward,hospitalId:hospital,hospitalName}),{signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'침상 자료를 불러오지 못했습니다.');setAllowed(true);setHospitals(j.hospitals);setRooms(j.rooms);if(!hospital&&j.hospitals.length===1)setHospital(j.hospitals[0].id);}).catch(e=>{if(e.name!=='AbortError'){setAllowed(false);setError(e.message)}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort();},[building,ward,hospital,hospitalName]);
 useEffect(()=>{if(slot)dialog.current?.showModal();else dialog.current?.close()},[slot]);
 function open(n:number){setError('');setMessage('');setDraft(current?.beds[n]||{number:String(n),patient:'',caregiver:''});setSlot(n);}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{
  const res=await fetch('/api/ward-assignments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hospitalId:hospital,building,ward,room:current?.room||roomName.trim(),version:current?.version||0,slot,capacity,toilet,...draft})});
  const j=await res.json();if(!res.ok)throw Error(j.error||'저장하지 못했습니다.');
  setRooms(prev=>[...prev.filter(r=>r.id!==j.room.id),j.room]);setSelected(j.room.id);setRoomName(j.room.room);setMessage(`${j.room.room} · ${draft.number}번 침상 저장이 완료되었습니다.`);setSlot(0);
 }catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setSaving(false)}}
 return <section className="bed-assignment-area" aria-label="침상 배정 입력">
 {loading?<p role="status">침상 자료 확인 중…</p>:allowed?<><div className="ward-layout-controls"><label>배정 병원<select value={hospital} onChange={e=>setHospital(e.target.value)}><option value="">병원을 선택하세요</option>{hospitals.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>저장된 병실<select value={selected} onChange={e=>{setSelected(e.target.value);const r=rooms.find(r=>r.id===e.target.value);setRoomName(r?.room||'');setError('');setMessage('');if(r)onLayout(r.capacity,r.toilet)}}><option value="">새 병실 입력</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.room}</option>)}</select></label></div>{!selected&&<label className="ward-notes">실제 병실명<input maxLength={40} value={roomName} onChange={e=>setRoomName(e.target.value)} placeholder="현장의 실제 병실명을 입력하세요"/></label>}<p>침상을 눌러 번호와 이름을 입력하세요. 저장 시 병실 종류와 화장실 위치도 함께 저장됩니다.</p></>:<p>{error}</p>}
 {message&&<p className="bed-save-success" role="status">{message}</p>}{error&&allowed&&!slot&&<p role="alert">{error}</p>}
 <div className="bed-layout"><span className="bed-center-aisle">중앙 통로</span><div className="ward-beds">{Array.from({length:Math.ceil(capacity/2)},(_,i)=>[Math.ceil(capacity/2)-i,Math.ceil(capacity/2)+i+1]).flat().filter(n=>n<=capacity).map(n=>{const b=current?.beds[n];return <button type="button" className={n<=Math.ceil(capacity/2)?'head-left':'head-right'} key={n} disabled={!allowed||loading||!hospital} onClick={()=>open(n)} aria-label={`${b?.number||n}번 침상 · ${b?.patient||'환자 미등록'} · ${b?.caregiver||'간병인 미배정'} · 수정`}><i aria-hidden="true"/><b>{b?.number||n}번 침상</b><span>환자명: {b?.patient||'등록 전'}</span><span>간병인: {b?.caregiver||'미배정'}</span></button>})}</div></div>
 <dialog ref={dialog} className="bed-edit-dialog" onCancel={e=>{e.preventDefault();if(!saving)setSlot(0)}}><form onSubmit={save}><h3>침상 정보 입력</h3><p>{building} · {ward} · {current?.room||roomName||'새 병실'}</p>{!selected&&<label>실제 병실명<input required maxLength={40} value={roomName} onChange={e=>setRoomName(e.target.value)}/></label>}<label>현장 침상번호<input autoFocus required maxLength={20} value={draft.number} onChange={e=>setDraft({...draft,number:e.target.value})}/></label><label>환자명<input maxLength={80} value={draft.patient} onChange={e=>setDraft({...draft,patient:e.target.value})}/></label><label>간병인 이름<input maxLength={80} value={draft.caregiver} onChange={e=>setDraft({...draft,caregiver:e.target.value})}/></label><small>이름을 비우고 저장하면 해당 침상의 배정이 해제됩니다. 이름 입력만으로 계정 접근 권한이나 계약이 변경되지는 않습니다.</small>{error&&<p role="alert">{error}</p>}<div className="bed-edit-actions"><button type="button" disabled={saving} onClick={()=>setSlot(0)}>취소 · 닫기</button><button type="submit" disabled={saving}>{saving?'저장 중…':'저장'}</button></div></form></dialog>
 </section>;
}

