"use client";
import {hospitalFetch as fetch} from "@/lib/hospital-fetch";
import { useEffect, useState } from "react";
import { Camera, Newspaper, Plus, Trash2, Upload, Video, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import "./board.css";

type Media={fileName:string;mimeType:string;size:number;storageKey:string};
type Post={id:number;title:string;content:string;author:string;attachments:Media[];createdAt:string};
export default function BoardModal({type,onClose}:{type:"공지사항"|"간병뉴스";onClose:()=>void}){
  const[posts,setPosts]=useState<Post[]>([]),[writing,setWriting]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function load(){try{const r=await fetch(`/api/board-posts?type=${encodeURIComponent(type)}`,{cache:"no-store"}),j=await r.json();if(r.ok)setPosts(j.posts||[]);else setMessage(j.error)}catch{setMessage("게시글을 불러오지 못했습니다.")}}
  useEffect(()=>{load()},[type]);
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,data=new FormData(form);data.set("boardType",type);try{const r=await fetch("/api/board-posts",{method:"POST",body:data}),j=await r.json();if(!r.ok)throw Error(j.error);form.reset();setWriting(false);setMessage("게시글이 등록되었습니다.");await load()}catch(e){setMessage(e instanceof Error?e.message:"저장하지 못했습니다.")}finally{setBusy(false)}}
  async function remove(id:number){if(!window.confirm("이 게시글과 첨부파일을 삭제하시겠습니까?"))return;setBusy(true);try{const r=await fetch("/api/board-posts",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id,boardType:type})}),j=await r.json();if(!r.ok)throw Error(j.error);await load()}catch(e){setMessage(e instanceof Error?e.message:"삭제하지 못했습니다.")}finally{setBusy(false)}}
  return <div className="board-backdrop" role="presentation" onClick={onClose}><section className="board-modal" role="dialog" aria-modal="true" aria-label={type} onClick={e=>e.stopPropagation()}><header><div>{type==="공지사항"?<Upload/>:<Newspaper/>}<span><b>{type}</b><small>관리자 게시판</small></span></div><div><Button type="button" onClick={()=>setWriting(!writing)}><Plus/>{writing?"글쓰기 닫기":"관리자 글쓰기"}</Button><button type="button" className="board-close" aria-label="닫기" onClick={onClose}><X/></button></div></header>{writing&&<form className="board-editor" onSubmit={save}><div><label>작성자<Input name="author" defaultValue="관리자" required/></label><label className="board-title-field">제목<Input name="title" required placeholder={`${type} 제목을 입력하세요`}/></label></div><label>내용<textarea name="content" required rows={7} placeholder="게시할 내용을 작성하세요"/></label><label className="board-upload"><span><Camera/>사진 첨부 <Video/>동영상 첨부</span><small>사진·동영상 여러 개 선택 가능 · 파일당 100MB 이하</small><input name="media" type="file" accept="image/*,video/*" multiple/></label><Button type="submit" disabled={busy}>{busy?"저장 중...":"글과 첨부파일 저장"}</Button></form>}{message&&<p className="board-message">{message}</p>}<div className="board-list">{posts.length===0?<div className="board-empty"><Newspaper/><b>등록된 {type}이 없습니다.</b><span>관리자 글쓰기로 첫 게시글을 등록하세요.</span></div>:posts.map(post=><article key={post.id}><div className="post-heading"><span><b>{post.title}</b><small>{post.author} · {new Date(post.createdAt.replace(" ","T")+"Z").toLocaleString("ko-KR")}</small></span><button type="button" onClick={()=>remove(post.id)} disabled={busy} aria-label="게시글 삭제"><Trash2/></button></div><p>{post.content}</p>{post.attachments.length>0&&<div className="post-media">{post.attachments.map(file=>file.mimeType.startsWith("image/")?<figure key={file.storageKey}><img src={`/api/board-media?key=${encodeURIComponent(file.storageKey)}`} alt={file.fileName}/><figcaption>{file.fileName}</figcaption></figure>:<figure key={file.storageKey}><video controls preload="metadata"><source src={`/api/board-media?key=${encodeURIComponent(file.storageKey)}`} type={file.mimeType}/></video><figcaption>{file.fileName}</figcaption></figure>)}</div>}</article>)}</div></section></div>
}
