"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
const labels=[['condition','환자 상태'],['care','간병 내용'],['meals','식사·수분 섭취'],['elimination','배뇨·배변'],['mobility','이동·체위 변경'],['notes','특이사항·인계 내용']];
export default function CareDiary({id,workflow,onSaved}:{id:number;workflow:any;onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const refresh=useRef(onSaved);refresh.current=onSaved;useEffect(()=>{let pending=false;const timer=window.setInterval(async()=>{if(pending)return;pending=true;try{await refresh.current()}catch{}finally{pending=false}},10000);return()=>window.clearInterval(timer)},[id]);
 async function act(action:string,body:any){setBusy(true);setMessage('');try{const r=await fetch('/api/care-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,...body})}),j=await r.json();if(!r.ok)throw Error(j.error);setMessage(action==='instruct_diary'?'담당 간병인에게 업무 지시를 등록했습니다.':action==='review_diary'?'일지 확인을 완료했습니다.':'지시 확인을 기록했습니다.');await onSaved();return true}catch(e){setMessage(e instanceof Error?e.message:'처리하지 못했습니다.');return false}finally{setBusy(false)}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setMessage('');try{const body=Object.fromEntries(new FormData(form));const r=await fetch('/api/care-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,id,action:'save_diary'})});const j=await r.json();if(!r.ok)throw Error(j.error);form.reset();setOpen(false);setMessage('간병일지를 저장했습니다. 협회(간병24) 관리자가 확인할 수 있습니다.');await onSaved()}catch(e){setMessage(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 return <section className="care-diary" aria-label="간병일지"><h4>간병일지 · 확인 및 업무 지시</h4><p>협회(간병24)와 담당 간병인이 확인하는 공간입니다. 새 일지와 지시는 10초마다 갱신됩니다.</p>{!workflow.startedAt?<p>약속한 근무 시간에 ‘근무 시작 확인’을 누르면 담당 간병인이 일지를 작성할 수 있습니다.</p>:<p>간병 시작: {new Date(workflow.startedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>}{!workflow.admin&&<Button type="button" disabled={!workflow.canWriteDiary} onClick={()=>setOpen(true)}>간병일지 작성</Button>}<p role="status">{message}</p>{open&&workflow.canWriteDiary&&<form onSubmit={save}><p>의뢰 {id}번 · 기록 시각은 저장할 때 자동으로 남습니다.</p>{labels.map(([key,label])=><label key={key}>{label}{['condition','care'].includes(key)?' *':''}<textarea name={key} required={['condition','care'].includes(key)} maxLength={4000}/></label>)}<div className="workflow-actions"><Button type="submit" disabled={busy}>간병일지 저장</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>작성 닫기</Button></div></form>}<div className="diary-records"><h5>저장된 간병일지 ({workflow.diary?.length||0}건)</h5>{!workflow.diary?.length&&<p>아직 작성된 일지가 없습니다.</p>}{[...(workflow.diary||[])].reverse().map((entry:any)=><details key={entry.id}><summary>{new Date(entry.recordedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · {entry.authorName} · {entry.reviewedAt?"관리자 확인 완료":"관리자 확인 대기"}{entry.instructions?.some((x:any)=>!x.acknowledgedAt)?" · 미확인 지시 있음":""}</summary>{labels.map(([key,label])=>entry[key]&&<p key={key}><b>{label}</b><span>{entry[key]}</span></p>)}<div className="diary-review"><p>{entry.reviewedAt?`확인: ${entry.reviewerName} · ${new Date(entry.reviewedAt).toLocaleString('ko-KR')}`:'협회(간병24) 확인 대기'}</p>{workflow.admin&&<><Button type="button" disabled={busy||!!entry.reviewedAt} onClick={()=>act('review_diary',{diaryId:entry.id})}>{entry.reviewedAt?'일지 확인 완료':'일지 확인 완료 처리'}</Button><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const content=new FormData(form).get('instruction');if(await act('instruct_diary',{diaryId:entry.id,content}))form.reset()}}><label>담당 간병인에게 업무 지시<textarea name="instruction" required maxLength={4000}/></label><Button type="submit" disabled={busy}>업무 지시 보내기</Button></form></>}<h5>협회(간병24) 업무 지시 ({entry.instructions?.length||0}건)</h5>{entry.instructions?.map((instruction:any)=><article key={instruction.id} className="diary-instruction"><b>{instruction.authorName} · {new Date(instruction.createdAt).toLocaleString('ko-KR')}</b><span>{instruction.content}</span><p>{instruction.acknowledgedAt?`간병인 확인: ${new Date(instruction.acknowledgedAt).toLocaleString('ko-KR')}`:'간병인 확인 대기'}</p>{workflow.canWriteDiary&&!instruction.acknowledgedAt&&<Button type="button" disabled={busy} onClick={()=>act('ack_instruction',{diaryId:entry.id,instructionId:instruction.id})}>지시 확인했습니다</Button>}</article>)}<small>‘지시 확인’은 읽음 확인이며, 업무 수행 완료를 뜻하지 않습니다.</small></div></details>)}</div></section>
}
