"use client";
import {useEffect,useState} from 'react';
import styles from './contribution.module.css';
type Money={paid:number;refunded:number;net:number;contribution:number;disbursed:number;remaining:number;overpaid:number};
type Month=Money&{hospitalId:string|null;hospitalName:string;month:string;dueOn:string;closed:boolean};
type Data={weekly:Money;weekRange:{start:string;end:string};admin:boolean;today:string;month:string;year:string;hospitalId:string|null;hospitalName:string;account:{bank:string;account:string;holder:string}|null;monthly:Money;annual:Money;allTime:Money;rows:Month[];byHospital:{id:string|null;name:string;weekly:Money;monthly:Money;annual:Money}[];entries:{id:string;reference:string;kind:string;amount:number;paid_on:string}[];hospitals:{id:string;name:string}[]};
const won=(n:number)=>n.toLocaleString('ko-KR')+'원';
const currentMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7);
export default function Contribution({hospitalId}:{hospitalId?:string}){
 const [week,setWeek]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[selected,setSelected]=useState(''),[month,setMonth]=useState(currentMonth),[year,setYear]=useState(()=>currentMonth().slice(0,4)),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[restricted,setRestricted]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[kind,setKind]=useState('payment'),[version,setVersion]=useState(0);
 const scope=hospitalId||selected,url='/api/contribution?month='+month+'&year='+year+'&week='+week+(scope?'&hospital='+encodeURIComponent(scope):'');
 useEffect(()=>{let live=true;let controller:AbortController;setData(null);setError('');setRestricted(false);async function load(){controller?.abort();controller=new AbortController();try{const r=await fetch(url,{cache:'no-store',signal:controller.signal});if(!live)return;if(r.status===401||r.status===403){setData(null);setRestricted(true);return;}const d=await r.json();if(!r.ok)throw Error(d.error||'집계 실패');if(live){setData(d);setError('');}}catch(e){if(live&&!(e instanceof Error&&e.name==='AbortError'))setError('최신 현황을 불러오지 못했습니다. 표시된 금액은 이전 값일 수 있습니다.');}}load();const timer=setInterval(load,5000);return()=>{live=false;controller?.abort();clearInterval(timer);};},[url,version]);
 async function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setMessage('');try{const input:Record<string,unknown>=Object.fromEntries(f);input.action=action;input.confirmed=f.get('confirmed')==='on';if(action!=='account')input.amount=Number(f.get('amount'));if(action==='payment')input.kind=kind;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const d=await r.json();if(!r.ok)throw Error(d.error||'저장 실패');form.reset();setMessage(action==='account'?'병원 지정 계좌를 저장했습니다.':action==='payout'?'관리자가 확인한 실제 이체 내역을 기록했습니다.':'입금·환불 내역을 저장했습니다.');setVersion(v=>v+1);}catch(e){setMessage(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
 if(restricted||!data?.admin)return null;
 return <section className={"care24-contribution "+styles.summary}><h2>{data?.hospitalName||'병원별'} 나눔 현황</h2><p>병원별 월간 순입금액의 1%를 집계하고 익월 5일을 지급 예정일로 표시합니다.</p><p role="status">{message}</p>{error&&<p role="alert">{error}</p>}
 <div style={{display:'flex',gap:16,flexWrap:'wrap',margin:'16px 0'}}><label>조회 주(기준일) <input type="date" value={week} onChange={e=>{if(e.target.value)setWeek(e.target.value);}}/></label><label>조회 월 <input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><label>조회 연도 <input type="number" min="2000" max="2100" value={year} onChange={e=>{if(/^\d{4}$/.test(e.target.value))setYear(e.target.value);}}/></label>{!hospitalId&&(selected?<button type="button" onClick={()=>{setSelected('');setMessage('');}}>전체 병원 보기</button>:<label>병원 선택 <select value={selected} onChange={e=>{setSelected(e.target.value);setMessage('');}}><option value="">전국 전체</option>{data?.hospitals.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>)}</div>
 {!data?<p>현황을 불러오는 중입니다.</p>:<><p>{data.weekRange.start} ~ {data.weekRange.end} · 월요일~일요일</p><div className="contribution-amounts"><div><span>주간 나눔 적립 참고액</span><strong>{won(data.weekly.contribution)}</strong><small>순입금액 {won(data.weekly.net)}</small></div><div><span>{month} 나눔 적립액</span><strong>{won(data.monthly.contribution)}</strong></div><div><span>{year}년 누적 적립액</span><strong>{won(data.annual.contribution)}</strong></div><div><span>전체 기간 누적 적립액</span><strong>{won(data.allTime.contribution)}</strong></div></div><p>{month} 순입금액 {won(data.monthly.net)} · 해당 월분 지급 확인 {won(data.monthly.disbursed)} / {year}년분 지급 확인 누적 {won(data.annual.disbursed)}</p>
 <p className="contribution-note">주간 1%는 참고액이며 지급 정산은 월별로 합니다. 월별 (확인된 간병비 입금 − 해당 입금의 환불) × 1%, 병원별·월별 원 미만 버림 후 합산합니다. 환불은 원래 입금 월에 반영됩니다. 지급 후 환불은 초과 지급 조정 대상으로 표시합니다. 금액은 관리자만 열람할 수 있습니다.</p>
 <p role="status" style={{padding:14,background:'#fff3d4',borderRadius:8}}><strong>자동송금 미연결</strong> · 익월 5일은 지급 예정일입니다. 실제 송금은 은행에서 진행하고, 거래내역을 확인한 뒤 아래에 기록하세요. 계좌 등록만으로 자동 출금되거나 입금 완료 처리되지 않습니다.</p>
 {!scope&&<><h3>병원별 주·월·년 누적금액</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>병원</th><th>주간 순입금 / 1% 참고액</th><th>{month} 적립</th><th>{year}년 누적 적립</th><th>{year}년분 지급 확인</th></tr></thead><tbody>{data.byHospital.map(h=><tr key={h.id||'unassigned'}><th>{h.name}</th><td>{won(h.weekly.net)} / {won(h.weekly.contribution)}</td><td>{won(h.monthly.contribution)}</td><td>{won(h.annual.contribution)}</td><td>{won(h.annual.disbursed)}</td></tr>)}</tbody></table></div><p>해당 기간의 입금·지급 내역이 있는 병원만 표시합니다. 병원을 선택하면 지정 계좌와 입금·지급 내역을 관리할 수 있습니다.</p></>}
 <h3>{year}년 월별 집계·지급 예정</h3><div style={{overflowX:'auto'}}><table><thead><tr>{!scope&&<th>병원</th>}<th>입금 기준월</th><th>나눔 적립액</th><th>지급 예정일</th><th>지급 확인</th><th>미지급</th><th>상태</th></tr></thead><tbody>{data.rows.map(r=><tr key={(r.hospitalId||'unassigned')+r.month}>{!scope&&<th>{r.hospitalName}</th>}<td>{r.month}</td><td>{won(r.contribution)}</td><td>{r.dueOn}</td><td>{won(r.disbursed)}</td><td>{won(r.remaining)}</td><td>{!r.hospitalId?'병원 배분 확인 필요':r.overpaid?`환불 후 초과 지급 ${won(r.overpaid)} · 조정 필요`:!r.closed?'집계 중':r.remaining===0?'지급 확인 완료 또는 지급액 없음':r.dueOn>data.today?'지급 예정':'지급일 도래 · 은행 이체 확인 필요'}</td></tr>)}</tbody></table></div>{!data.rows.length&&<p>이 기간에 확인된 입금·지급 내역이 없습니다.</p>}
 {scope&&<><h3>이 병원이 지정한 나눔 수령 계좌</h3>{data.account?<p>{data.account.bank} {data.account.account} · 예금주 {data.account.holder}</p>:<p>병원 지정 계좌 미등록</p>}
 <details className="contribution-admin"><summary>병원 지정 계좌 등록·수정</summary><form onSubmit={e=>submit(e,'account')}><label>은행<input name="bank" required maxLength={50} defaultValue={data.account?.bank}/></label><label>계좌번호<input name="account" required pattern="[0-9][0-9-]{5,39}" defaultValue={data.account?.account}/></label><label>예금주<input name="holder" required maxLength={100} defaultValue={data.account?.holder}/></label><label><input type="checkbox" name="confirmed" required/>해당 병원이 지정한 수령 계좌임을 확인했습니다.</label><button disabled={busy}>지정 계좌 저장</button></form></details>
 <details className="contribution-admin"><summary>관리자: 이 병원 간병비 입금·환불 등록</summary><form onSubmit={e=>submit(e,'payment')}><label>기록 종류<select value={kind} onChange={e=>setKind(e.target.value)}><option value="payment">입금 확인</option><option value="refund">환불 확인</option></select></label>{kind==='refund'&&<label>원래 입금<select name="paymentId" required><option value="">선택하세요</option>{data.entries.filter(e=>e.kind==='payment').map(e=><option key={e.id} value={e.id}>{e.paid_on} · {e.reference} · {won(Number(e.amount))}</option>)}</select></label>}<label>거래번호 또는 관리번호<input name="reference" required maxLength={100}/></label><label>실제 처리일<input name="paidOn" type="date" max={data.today} required/></label><label>금액(원)<input name="amount" type="number" min="1" max="1000000000000" step="1" required/></label><label><input type="checkbox" name="confirmed" required/>이 병원의 실제 입금·환불 내역을 확인했습니다.</label><button disabled={busy}>확인한 내역 저장</button></form></details>
 <details className="contribution-admin"><summary>관리자: 은행에서 완료한 나눔 이체 기록</summary><form onSubmit={e=>submit(e,'payout')}><p>송금 버튼이 아닙니다. 아래 미지급액과 같은 금액을 지정 계좌로 이체한 내역만 기록하세요.</p><label>지급 대상월<select name="month" required><option value="">선택하세요</option>{data.rows.filter(r=>r.closed&&r.remaining>0&&!r.overpaid&&r.dueOn<=data.today).map(r=><option key={r.month} value={r.month}>{r.month} · 미지급 {won(r.remaining)}</option>)}</select></label><label>실제 이체금액<input name="amount" type="number" min="1" step="1" required/></label><label>은행 거래번호<input name="reference" required maxLength={100}/></label><label>실제 이체일<input name="paidOn" type="date" max={data.today} required/></label><label><input type="checkbox" name="confirmed" required/>지정 계좌로 입금 완료된 은행 거래내역을 확인했습니다.</label><button disabled={busy||!data.account}>실제 이체 확인 기록</button></form></details><p>입금·환불·이체 번호에 환자 이름이나 개인정보를 넣지 마세요.</p></>}
 </>}
 </section>;
}
