"use client";
import {hospitalFetch as fetch} from "@/lib/hospital-fetch";
import { useEffect, useState } from "react";
import { Phone, BarChart3, CalendarDays, CheckCircle2, Clock3, HeartHandshake, RefreshCw, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import "./matching.css";
import RequestWorkflow from "./request-workflow";
import "./security.css";
import {splitRehabilitationNotes,joinRehabilitationNotes} from "@/lib/rehabilitation-notes.mjs";

type RequestRow = { canPrepareContract?:boolean; id:number; contractNumber:string; building:string; floorName:string; ward:string; patientGender:string; patientAge?:string; patientBirthYear?:string; patientWeight?:string; patientName:string; diagnosis:string; patientCondition:string; precautions:string; specialNotes:string; desiredGender:string; desiredNationality:string; desiredExpertise:string; desiredAge:string; desiredPersonality:string; desiredOther:string; status:string };
type Profile = { id:number; applicantName:string; applicantGender:string; careerYears:string; qualification:string; preferredDate:string };
type Stats = Record<"day"|"week"|"month"|"year",{total:number;matched:number}>;
const statusText:Record<string,string>={requesting:"간병의뢰중",matching:"신청 접수·선정 중",matched:"매칭완료"};
const emptyStats:Stats={day:{total:0,matched:0},week:{total:0,matched:0},month:{total:0,matched:0},year:{total:0,matched:0}};
const sampleRequests:Record<string,RequestRow[]>={
  "1동":[
    {id:-101,contractNumber:"예시 계약서 01",building:"1동",floorName:"7층",ward:"1병동",patientGender:"여",patientName:"김○○",diagnosis:"고관절 수술 후 회복",patientCondition:"보행 보조 필요",precautions:"낙상 주의",specialNotes:"야간 관찰",desiredGender:"여성",desiredNationality:"무관",desiredExpertise:"재활 간병 경험",desiredAge:"50~60대",desiredPersonality:"차분함",desiredOther:"책임감",status:"requesting"},
    {id:-102,contractNumber:"예시 계약서 02",building:"1동",floorName:"9층",ward:"2병동",patientGender:"남",patientName:"박○○",diagnosis:"뇌졸중 회복기",patientCondition:"부분 도움 필요",precautions:"연하 주의",specialNotes:"체위 변경",desiredGender:"남성",desiredNationality:"한국",desiredExpertise:"뇌신경·재활 경험",desiredAge:"무관",desiredPersonality:"친절함",desiredOther:"",status:"matching"},
  ],
  "2동":[
    {id:-201,contractNumber:"예시 계약서 03",building:"2동",floorName:"8층",ward:"재활병동",patientGender:"여",patientName:"이○○",diagnosis:"척추 수술 후 회복",patientCondition:"이동 보조 필요",precautions:"보조기 착용",specialNotes:"재활 일정 준수",desiredGender:"여성",desiredNationality:"무관",desiredExpertise:"재활 환자 경험",desiredAge:"40~60대",desiredPersonality:"밝고 성실함",desiredOther:"",status:"requesting"},
    {id:-202,contractNumber:"예시 계약서 04",building:"2동",floorName:"9층",ward:"완화의료병동",patientGender:"남",patientName:"최○○",diagnosis:"회복·안정 관리",patientCondition:"상시 관찰 필요",precautions:"감염 예방",specialNotes:"정서 지원",desiredGender:"무관",desiredNationality:"한국",desiredExpertise:"중증환자 경험",desiredAge:"50대 이상",desiredPersonality:"침착함",desiredOther:"야간 가능",status:"matching"},
  ],
};
function CareRequestForm({onSubmit,busy,initial={},editingId,onCancel,contactHidden=false,customHospital=false,message=""}:{message?:string;customHospital?:boolean;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean;initial?:Record<string,string>;editingId?:number;contactHidden?:boolean;onCancel:()=>void}){
  initial={...initial,...splitRehabilitationNotes(initial.specialNotes)};
  const [rehabStatus,setRehabStatus]=useState(initial.rehabStatus||"");
  const currentYear=new Date().getFullYear(); const [birthYear,setBirthYear]=useState(initial.patientBirthYear||""),[patientAge,setPatientAge]=useState(initial.patientAge||"");
  const [validationMessage,setValidationMessage]=useState("");
  const [roomStatus,setRoomStatus]=useState(initial.room?.startsWith("응급실 대기 중")?"emergency_waiting":"assigned");
  return <form id="patient-care-request" className="request-form" aria-labelledby="patient-care-request-title" onInvalid={()=>setValidationMessage("필수 항목과 공개 동의를 확인해 주세요. 표시된 입력란을 작성한 뒤 다시 저장하세요.")} onSubmit={e=>{setValidationMessage("");onSubmit(e)}}><h3 id="patient-care-request-title" tabIndex={-1}>환자·보호자용 간병 의뢰서{editingId?` · 의뢰 ${editingId} 수정`:""}</h3>{editingId&&<p>같은 의뢰번호로 수정합니다. 기존 신청·계약 진행은 유지됩니다. 계약 조건이 달라지면 협회에 별도로 알려 주세요.</p>}<div className="request-grid">
    <label>의뢰인 성명<Input name="requesterName" required defaultValue={initial.requesterName??""}/></label><label>연락처 · 관리자만 열람<Input name="requesterPhone" type="tel" required={!contactHidden} defaultValue={contactHidden?"":initial.requesterPhone??""} placeholder={contactHidden?"비공개 · 변경할 때만 새 번호 입력":"연락처 입력"}/><small>{contactHidden?"저장된 번호는 공개되지 않습니다. 빈칸으로 저장하면 기존 번호가 유지됩니다.":"저장된 연락처는 관리자만 확인하며 간병인·일반인에게 공개되지 않습니다."}</small></label><label>환자 성명<Input name="patientName" required defaultValue={initial.patientName??""}/></label><fieldset className="gender-choice"><legend>환자 성별</legend><label><input type="radio" name="patientGender" value="남" required defaultChecked={initial.patientGender==="남"}/>남성</label><label><input type="radio" name="patientGender" value="여" required defaultChecked={initial.patientGender==="여"}/>여성</label></fieldset><label>환자 출생연도<select className="birth-year-select" name="patientBirthYear" size={5} required value={birthYear} onChange={e=>{setBirthYear(e.target.value);setPatientAge(String(currentYear-Number(e.target.value)))}}><option value="" disabled>출생연도 선택</option>{Array.from({length:121},(_,i)=>currentYear-i).map(year=><option key={year} value={year}>{year}년</option>)}</select><small>목록을 위아래로 움직여 선택하세요.</small></label><label>환자 나이<Input name="patientAge" type="number" min="0" max="120" inputMode="numeric" required value={patientAge} onChange={e=>setPatientAge(e.target.value)}/><small>출생연도로 계산한 나이입니다. 생일에 따라 정확한 나이로 수정하세요.</small></label><label>환자 체중 (kg)<Input name="patientWeight" type="number" min="1" max="300" step="0.1" inputMode="decimal" required placeholder="예: 62.5" defaultValue={initial.patientWeight??""}/></label><label>진단명<Input name="diagnosis" required placeholder="공개 동의한 범위로 기재" defaultValue={initial.diagnosis??""}/></label><label>환자 상태<Input name="patientCondition" required placeholder="예: 보행 보조 필요" defaultValue={initial.patientCondition??""}/></label>
    <label>동명{customHospital?<Input name="building" required placeholder="입원 건물명" defaultValue={initial.building??""}/>:<select name="building" required defaultValue={initial.building??"1동"}><option>1동</option><option>2동</option></select>}</label><label>층별명<Input name="floorName" required placeholder="예: 7층" defaultValue={initial.floorName??""}/></label><label>병동명<Input name="ward" required placeholder="예: 1병동" defaultValue={initial.ward??""}/></label>
    <label className="room-status-field">병실 배정 상태<select name="roomStatus" value={roomStatus} onChange={e=>setRoomStatus(e.target.value)}><option value="assigned">병실 배정 완료</option><option value="emergency_waiting">응급실 대기 중 (병실 미배정·간병인 미지정)</option></select></label>
    <label className={roomStatus==="emergency_waiting"?"room-number-field waiting":"room-number-field"}>병실<Input name="room" disabled={roomStatus==="emergency_waiting"} required={roomStatus==="assigned"} placeholder={roomStatus==="emergency_waiting"?"응급실 대기 중":"예: 701호 (비공개 저장)"} defaultValue={initial.room??""}/><small>{roomStatus==="emergency_waiting"?"병실에 올라가기 전 대기 상태로 저장됩니다.":"정확한 병실은 공개 목록에 표시되지 않습니다."}</small></label>
    <fieldset className="rehabilitation-fields wide"><legend>재활치료 및 간병 도움</legend><p>현재 치료 계획에 맞춰 작성해 주세요. 간병인에게 필요한 이동·동행 도움을 알려주세요.</p><div className="request-grid">
      <label>재활치료 여부<select name="rehabStatus" value={rehabStatus} onChange={e=>setRehabStatus(e.target.value)}><option value="">선택 안 함</option><option>치료 중</option><option>치료 예정</option><option>확인 필요</option><option>없음</option></select></label>
      {rehabStatus&&rehabStatus!=="없음"&&<><label>치료 종류<Input name="rehabType" maxLength={300} placeholder="예: 물리치료, 작업치료, 언어치료" defaultValue={initial.rehabType||""}/></label><label>치료 일정·장소<Input name="rehabSchedule" maxLength={300} placeholder="예: 평일 오전 / 재활치료실 · 미정이면 미정" defaultValue={initial.rehabSchedule||""}/></label><label>이동·동행 도움<Input name="rehabAssistance" maxLength={300} placeholder="예: 휠체어 이동, 치료실 왕복 동행" defaultValue={initial.rehabAssistance||""}/></label><label className="wide">재활 관련 주의사항<Input name="rehabPrecautions" maxLength={500} placeholder="의료진이 안내한 주의사항을 적어주세요." defaultValue={initial.rehabPrecautions||""}/></label></>}
      <small className="wide">재활치료는 의료진이 시행하며, 간병인은 안내받은 범위에서 이동·동행과 일상생활을 돕습니다. 작성한 재활 정보는 공개 동의 후 의뢰의 특이사항에 함께 표시됩니다.</small>
    </div></fieldset>
    <label>주의사항<Input name="precautions" placeholder="예: 낙상 주의" defaultValue={initial.precautions??""}/></label><label>특이사항<Input name="specialNotes" placeholder="예: 야간 관찰" defaultValue={initial.specialNotes??""}/></label><label>간병 구분<select name="careType" required defaultValue={initial.careType??"개인간병"}><option>개인간병</option><option>공동간병</option></select></label><label>간병 시작일<Input name="startDate" type="date" required defaultValue={initial.startDate??""}/></label><div className="preference-title wide"><b>희망 간병인 조건</b><span>무관을 선택하거나 원하는 조건을 공개할 수 있습니다.</span></div><label>희망 성별<select name="desiredGender" defaultValue={initial.desiredGender??"무관"}><option>무관</option><option>여성</option><option>남성</option></select></label><label>희망 국적<select name="desiredNationality" defaultValue={initial.desiredNationality??"무관"}><option>무관</option><option>한국</option><option>중국</option><option>기타</option></select></label><label>희망 나이대<select name="desiredAge" defaultValue={initial.desiredAge??"무관"}>{initial.desiredAge&&!["무관","30대","40대","50대","60대","70대"].includes(initial.desiredAge)&&<option>{initial.desiredAge}</option>}<option>무관</option><option>30대</option><option>40대</option><option>50대</option><option>60대</option><option>70대</option></select></label><label className="wide">희망 전문성<Input name="desiredExpertise" defaultValue={initial.desiredExpertise??"무관"}/></label><label className="wide">희망 성격<Input name="desiredPersonality" defaultValue={initial.desiredPersonality??"무관"}/></label><label className="wide">기타 공개조건<Input name="desiredOther" defaultValue={initial.desiredOther??""}/></label><label className="wide">요청사항<Input name="requestNote" placeholder="비공개 저장" defaultValue={initial.requestNote??""}/></label><label className="public-consent wide"><input type="checkbox" name="publicConsent" value="동의" required/><span><b>민감정보 공개 동의</b> 진단명·환자상태·주의사항·특이사항(재활치료 정보 포함)의 공개에 동의합니다. 출생연도·나이를 공개하며, 환자 이름은 가운데 글자를 가립니다. 연락처·정확한 병실·모든 금액은 비공개이며 관리자만 조회·수정합니다.</span></label>

  </div>{(validationMessage||message)&&<p className="matching-message" role="alert">{validationMessage||message}</p>}<Button type="submit" disabled={busy}>{busy?"저장 중…":editingId?"수정 후 저장·공개":"의뢰서 저장 및 공개"}</Button><Button type="button" variant="outline" onClick={onCancel} disabled={busy}>취소</Button></form>
}

export default function LiveMatching({requestSequence=0,hospitalId}:{requestSequence?:number;hospitalId?:string}){
  const [restricted,setRestricted]=useState(true);
  const [editing,setEditing]=useState<{id:number;request:Record<string,string>;contactHidden:boolean}|null>(null);
  const [savedRequest,setSavedRequest]=useState<number|null>(null);
  const [activeRequest,setActiveRequest]=useState<number|null>(null);
  const [progress,setProgress]=useState<{id:number;status:string}[]>([]);
  const [requests,setRequests]=useState<RequestRow[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[stats,setStats]=useState<Stats>(emptyStats),[formOpen,setFormOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[updated,setUpdated]=useState(""),[flashId,setFlashId]=useState<number|null>(null),[lastContract,setLastContract]=useState<string>("");
  async function load(){try{const r=await fetch("/api/care-requests",{cache:"no-store"}),j=await r.json();if(r.ok){setRestricted(j.restricted===true);setRequests(j.requests||[]);setProgress(j.progress||[]);setProfiles(j.profiles||[]);setStats(j.stats||emptyStats);setUpdated(new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}));}else{setMessage(j.error||"현황을 불러오지 못했습니다.")}}catch{setMessage("현황을 불러오지 못했습니다. 새로고침해 주세요.")}}
  useEffect(()=>{load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(requestSequence>0){setEditing(null);setFormOpen(true)}},[requestSequence]);
  useEffect(()=>{if(!formOpen)return;const frame=window.requestAnimationFrame(()=>{document.getElementById("patient-care-request")?.scrollIntoView({behavior:"instant",block:"start"});document.getElementById("patient-care-request-title")?.focus({preventScroll:true})});return()=>window.cancelAnimationFrame(frame)},[formOpen,requestSequence,editing]);
  useEffect(()=>{if(!flashId)return;const timer=window.setTimeout(()=>{const row=Array.from(document.querySelectorAll<HTMLElement>(".care-table-item")).find(item=>item.querySelector(".care-table-row>strong")?.textContent===String(flashId));if(!row)return;row.classList.add("just-applied");const badge=row.querySelector<HTMLElement>(".match-status");if(badge){badge.dataset.originalText=badge.textContent||"매칭상담중";badge.textContent="신청완료 · 매칭상담중"}},60);return()=>{window.clearTimeout(timer);document.querySelectorAll<HTMLElement>(".care-table-item.just-applied").forEach(item=>{item.classList.remove("just-applied");const badge=item.querySelector<HTMLElement>(".match-status");if(badge?.dataset.originalText)badge.textContent=badge.dataset.originalText})}},[flashId,requests]);
  async function editRequest(id:number){setMessage('');try{const r=await fetch('/api/care-requests/'+id,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setEditing({id,request:j.request,contactHidden:j.contactHidden});setFormOpen(true)}catch(e){setMessage(e instanceof Error?e.message:'불러오지 못했습니다.')}}
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,body=Object.fromEntries(new FormData(form));body.specialNotes=joinRehabilitationNotes(body);for(const key of Object.keys(body))if(key.startsWith("rehab"))delete body[key];try{const r=await fetch(editing?"/api/care-requests/"+editing.id:"/api/care-requests",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error);setSavedRequest(j.id);form.reset();setFormOpen(false);setEditing(null);setLastContract("");setMessage(editing?`의뢰 ${j.id}번이 수정·공개되었습니다. 같은 번호로 반영했습니다.`:`의뢰 ${j.id}번이 저장·공개되었습니다. 개인정보·간병비·계약서는 관리자만 조회·수정합니다.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"저장하지 못했습니다.")}finally{setBusy(false)}}
  function buildingTable(building:string){const realRows=requests.filter(x=>x.building===building),rows=realRows.length?realRows:(hospitalId||restricted)?[]:sampleRequests[building]||[];return <section className={`building-queue wide-building-table ${building==="1동"?"building-one":"building-two"}`} key={building}><header><div><strong>{building}</strong><span>실시간 간병의뢰</span></div><div><b>간병의뢰 {realRows.filter(x=>x.status==="requesting").length}</b><b>매칭완료 {realRows.filter(x=>x.status==="matched").length}</b></div></header>{!restricted&&!hospitalId&&!realRows.length&&<p className="sample-notice">실제 의뢰가 등록되기 전 표시되는 예시 2건입니다.</p>}<div className="wide-table-scroll"><div className="care-table-head"><b>번호</b><b>동명</b><b>층별명</b><b>병동명</b><b>환자 성별</b><b>이름 · 출생연도 · 나이</b><b>진단명</b><b>상태</b><b>주의사항</b><b>특이사항</b><b>원하는 간병인 조건</b><b>진행상태</b></div>{rows.map(x=>{const sample=x.id<0,condition=`성별 ${x.desiredGender} · 국적 ${x.desiredNationality} · 나이 ${x.desiredAge} · 전문성 ${x.desiredExpertise} · 성격 ${x.desiredPersonality}${x.desiredOther?` · 기타 ${x.desiredOther}`:""}`;return <article className={`care-table-item ${x.status}`} key={x.id}><div className="care-table-row"><strong>{sample?"예시":<button type="button" className="request-number" onClick={()=>setActiveRequest(x.id)} aria-label={`의뢰 ${x.id} 신청 및 진행 보기`}>{x.id}</button>}</strong><span>{x.building}</span><span>{x.floorName}</span><span>{x.ward}</span><span>{x.patientGender}</span><span>{x.patientName}<br/>{x.patientBirthYear ? `${x.patientBirthYear}년생` : "출생연도 미등록"}<br/>{x.patientAge ? `${x.patientAge}세` : "나이 미등록"}</span><span>{x.diagnosis}</span><span>{x.patientCondition}</span><span>{x.precautions||"-"}</span><span style={{whiteSpace:"pre-line"}}>{x.specialNotes||"-"}</span><span className="wanted-condition">{condition}</span><span className={`match-status ${x.status}`}>{statusText[x.status]}</span></div>{sample?<div className="sample-action">예시 자료</div>:<div className="profile-apply"><Button type="button" onClick={()=>setActiveRequest(x.id)}>의뢰 {x.id}번 · 간병 신청 / 상태 확인</Button>{x.canPrepareContract&&<Button type="button" onClick={()=>setActiveRequest(x.id)}>간병의뢰계약서 · 간병비 입력</Button>}</div>}</article>})}</div></section>}
  return <>
    {formOpen&&<CareRequestForm message={message} customHospital={!!hospitalId} key={editing?`request-edit-${editing.id}`:"request-new"} initial={editing?.request} contactHidden={editing?.contactHidden} editingId={editing?.id} onSubmit={create} busy={busy} onCancel={()=>{setFormOpen(false);setEditing(null)}}/>}
    {savedRequest&&!formOpen&&<section className="request-save-receipt" role="status"><h3>의뢰 {savedRequest}번 저장·공개 완료</h3><p>간병인이 아래 목록의 의뢰번호를 누르면 간병 신청서를 작성할 수 있습니다.</p><Button type="button" onClick={()=>setActiveRequest(savedRequest)}>의뢰 {savedRequest}번 · 진행 상태 확인</Button></section>}
    <section id="live-matching" className="live-matching">
    <header><div><p>실시간 간병 연결</p><h2>간병 의뢰·매칭 현황</h2><span><i></i>{updated?`${updated} 기준 · 5초마다 자동 갱신`:"현황 불러오는 중"}</span></div><div><Button type="button" variant="outline" onClick={load}><RefreshCw/>새로고침</Button></div></header>
    <div className="contract-flow-banner"><CheckCircle2/><span><b>의뢰 공개 → 간병인 신청 저장·보내기 → 협회 계약·통보 → 유니폼 수령 → 근무 시작</b><small>연락처·정확한 병실·간병비·계약서는 관리자만 조회·수정할 수 있습니다.</small></span></div>
    <div className="matching-security"><ShieldCheck/><div><b>동의 범위 안에서 공개</b><span>환자·보호자가 동의한 상태·주의사항과 희망 간병인 조건을 공개합니다. 출생연도·나이는 공개하며 환자 이름은 가운데 글자를 가리고, 연락처·정확한 병실·간병비·계약금액은 공개하지 않습니다.</span></div></div>
    {activeRequest!==null&&<RequestWorkflow key={`workflow-${activeRequest}`} id={activeRequest} profiles={profiles} onEdit={()=>editRequest(activeRequest)} onComplete={setMessage} onChange={load} onClose={()=>setActiveRequest(null)}/>}
    {!!progress.length&&<div className="workflow-progress"><h3>내 신청·계약·근무 진행</h3>{progress.map(x=><Button key={x.id} type="button" variant="outline" onClick={()=>setActiveRequest(x.id)}>의뢰 {x.id} · 진행 확인</Button>)}</div>}

    {message&&<p className="matching-message">{message}</p>}{lastContract&&<div className="auto-contract"><CheckCircle2/><div><b>간병 의뢰계약서 자동생성</b><span>계약번호 {lastContract} · 개인정보 비공개 저장 · 공개 동의 항목만 공개</span></div></div>}
    <div className="matching-workspace">
      <div className="matching-queue">
        <div className="today-queue-head"><div><span>오늘 접수</span><strong>{stats.day.total}건</strong></div><p><i></i>간병인이 새 의뢰를 확인하고 저장된 프로필로 바로 신청할 수 있습니다.</p></div>
        <div className="status-guide"><span className="requesting"><Clock3/>전체 간병의뢰 {requests.filter(x=>x.status==="requesting").length}</span><span className="matching"><UserRoundCheck/>전체 매칭상담 {requests.filter(x=>x.status==="matching").length}</span><span className="matched"><CheckCircle2/>오늘 매칭완료 {stats.day.matched}</span></div>
        <div className="building-queues">{(hospitalId?[...new Set(requests.map(r=>r.building))]:["1동","2동"]).map(buildingTable)}{hospitalId&&!requests.length&&<p className="empty">이 병원에 등록된 간병 의뢰가 없습니다. 위의 간병 의뢰 버튼으로 작성하세요.</p>}</div>
      </div>
      <aside className="matching-summary"><header><BarChart3/><div><b>누적 현황</b><span>실시간 자동 집계</span></div></header><div className="matching-stats">{[["일",stats.day],["주",stats.week],["월",stats.month],["년",stats.year]].map(([label,value]:any)=><article key={label}><CalendarDays/><span><b>{label} 누적 {value.total}건</b><small>매칭완료 {value.matched}건</small></span></article>)}</div></aside>
    </div>
  </section></>
}
