"use client";
import {useEffect,useState} from 'react';
import {careDepositAccounts} from '@/lib/care-deposit-accounts.mjs';
import styles from './contribution.module.css';
type Notice={canEdit?:boolean;id:string;requestId:number;hospitalId:string;status:string;reason:string;amount?:number;paidOn?:string;depositor?:string;account?:string;confirmedAt?:string};
type Data={role:string;canCreate:boolean;requests:{id:number;hospitalId:string}[];notices:Notice[]};
const labels:Record<string,string>={draft:'작성 중 · 미전송',pending:'입금 확인 대기',confirmed:'관리자 입금 확인 완료',returned:'재확인 요청'};
const empty=()=>({id:crypto.randomUUID(),requestId:'',amount:'',paidOn:'',depositor:'',account:''});
export default function PaymentNotices({hospitalId}:{hospitalId?:string}){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<ReturnType<typeof empty>|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0),[review,setReview]=useState(false);
 const url='/api/payment-notices'+(hospitalId?'?hospital='+encodeURIComponent(hospitalId):'');
 useEffect(()=>{setForm(empty());},[hospitalId]);
 useEffect(()=>{let live=true,controller:AbortController;async function load(){controller?.abort();controller=new AbortController();try{const response=await fetch(url,{cache:'no-store',signal:controller.signal});const body=await response.json();if(!response.ok){if(live)setData(null);throw Error(body.error||'통보 조회 실패');}if(live){setData(body);setError('');}}catch(e){if(live&&!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'조회 실패');}}load();const timer=setInterval(load,10000);return()=>{live=false;controller?.abort();clearInterval(timer);};},[url,version]);
 async function action(body:Record<string,unknown>){setBusy(true);setMessage('');try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error);setMessage(body.action==='confirm'?'은행 입금 확인을 기록했습니다. 주·월·년 누계에 반영됩니다.':body.action==='return'?'재확인을 요청했습니다.':body.action==='save'?'통보를 저장했습니다. 협회(간병24) 보내기를 눌러 제출해 주세요.':'입금 통보를 보냈습니다. 관리자 확인 후 누계에 반영됩니다.');if(body.action==='send'){setForm(empty());setReview(false);}setVersion(v=>v+1);}catch(e){setMessage(e instanceof Error?e.message:'처리 실패');}finally{setBusy(false);}}
 const set=(key:string,value:string)=>setForm(f=>f?{...f,[key]:value}:f);
 return <section className={styles.summary} aria-label="간병비 입금 통보"><h2>간병비 입금 통보</h2><p>입금 통보 → 관리자 은행내역 확인 → 입금 확인 완료 → 누적금액 반영</p><p>입금 통보만으로 입금 완료 처리되지 않습니다. 병원 담당자는 소속 병원의 진행 상태를 확인할 수 있습니다.</p>{error&&<p role="alert">{error}</p>}<p role="status">{message}</p>{data&&<><p>확인 대기 {data.notices.filter(n=>n.status==='pending').length}건 · 확인 완료 {data.notices.filter(n=>n.status==='confirmed').length}건</p>
 {data.role!=='hospital'&&<p>이 화면에 표시된 통보 중 확인된 입금 누계: <strong>{data.notices.filter(n=>n.status==='confirmed').reduce((s,n)=>s+Number(n.amount||0),0).toLocaleString('ko-KR')}원</strong> · 환불 차감 전 입금액입니다.</p>}
 {data.canCreate&&form&&<details><summary>환자·보호자: 입금 통보 작성</summary><p>본인 계정으로 작성한 의뢰를 선택하세요. 관리자가 대신 작성한 의뢰는 협회(간병24)에 문의해 주세요.</p><form onSubmit={e=>{e.preventDefault();action({...form,amount:Number(form.amount),requestId:Number(form.requestId),action:(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')||'save'});}}><label>의뢰번호<select required value={form.requestId} onChange={e=>set('requestId',e.target.value)}><option value="">의뢰 선택</option>{data.requests.map(r=><option key={r.id} value={r.id}>의뢰 {r.id}번</option>)}</select></label><label>실제 입금일<input type="date" required value={form.paidOn} onChange={e=>set('paidOn',e.target.value)}/></label><label>입금 금액(원)<input type="number" min="1" max="1000000000000" step="1" required value={form.amount} onChange={e=>set('amount',e.target.value)}/></label><label>입금자명<input required maxLength={80} value={form.depositor} onChange={e=>set('depositor',e.target.value)} placeholder="은행에 표시된 입금자명"/></label><label>입금한 계좌<select required value={form.account} onChange={e=>set('account',e.target.value)}><option value="">계좌 선택</option>{careDepositAccounts.map(a=><option key={a.account} value={a.account}>{a.bank} {a.account} · {a.holder}</option>)}</select></label><p>저장 → 보내기 → 확인</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button value="save" disabled={busy}>저장</button><button value="send" disabled={busy}>협회(간병24) 보내기</button><button type="button" disabled={busy} onClick={()=>setReview(v=>!v)}>확인</button></div>{review&&<p>의뢰 {form.requestId||'미선택'}번 · {form.paidOn||'날짜 미입력'} · {Number(form.amount||0).toLocaleString('ko-KR')}원 · {form.depositor||'입금자 미입력'} · {form.account||'계좌 미선택'}<br/>작성 내용을 확인하는 화면입니다. 은행 입금 확인 완료를 뜻하지 않습니다.</p>}</form></details>}
 <h3>{data.role==='hospital'?'소속 병원 입금 진행 상태':'입금 통보 내역'}</h3>{!data.notices.length&&<p>표시할 입금 통보가 없습니다.</p>}{data.notices.map(n=><article key={n.id} style={{background:'white',border:'1px solid #bdd4ce',borderRadius:10,padding:16,margin:'12px 0'}}><h3>의뢰 {n.requestId}번 · {labels[n.status]||n.status}</h3>{data.role!=='hospital'&&<p>{n.paidOn} · {Number(n.amount||0).toLocaleString('ko-KR')}원 · 입금자 {n.depositor}<br/>우리은행 {n.account}</p>}{n.reason&&<p>재확인 사유: {n.reason}</p>}{n.confirmedAt&&<p>관리자 확인일: {new Date(n.confirmedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>}{n.canEdit&&<button type="button" disabled={busy} onClick={()=>{setForm({id:n.id,requestId:String(n.requestId),amount:String(n.amount),paidOn:n.paidOn||'',depositor:n.depositor||'',account:n.account||''});setMessage('위의 입금 통보 작성 항목을 열어 수정 후 보내세요.');}}>불러와 수정</button>}
 {data.role==='admin'&&n.status==='pending'&&<><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action({id:n.id,action:'confirm',reference:f.get('reference'),confirmedAmount:Number(f.get('confirmedAmount')),bankChecked:f.get('bankChecked')==='on'});}}><label>은행에서 확인한 실제 금액<input type="number" name="confirmedAmount" min="1" step="1" required/></label><label>은행 거래번호<input name="reference" maxLength={100} required placeholder="기존 입금 장부와 동일한 거래번호 사용"/></label><label><input type="checkbox" name="bankChecked" required/>입금일·입금자·계좌·금액을 실제 은행 거래내역과 대조했습니다.</label><button disabled={busy}>관리자 입금 확인</button></form><form onSubmit={e=>{e.preventDefault();action({id:n.id,action:'return',reason:new FormData(e.currentTarget).get('reason')});}}><label>재확인 사유<select name="reason" required>{['은행 내역 미확인','입금일·금액 확인 필요','입금자·계좌 확인 필요','중복 통보'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy}>재확인 요청</button></form></>}
 </article>)}{data.role==='hospital'&&<p>개인정보와 입금 금액은 표시하지 않습니다. 입금 확인·누계 반영은 관리자만 처리합니다.</p>}</>}</section>;
}
