"use client";
import {useEffect,useState} from 'react';
import {careDepositAccounts} from '@/lib/care-deposit-accounts.mjs';
import styles from './contribution.module.css';
type Notice={canAcknowledge?:boolean;canEdit?:boolean;id:string;requestId:number;patientName:string;hospitalId:string;status:string;reason:string;amount?:number;paidOn?:string;careStart?:string;careEnd?:string;depositor?:string;account?:string;confirmedAt?:string};
type Data={summary?:{paid:number;refunded:number;net:number};role:string;canCreate:boolean;requests:{id:number;hospitalId:string;patientName:string}[];notices:Notice[]};
const labels:Record<string,string>={draft:'작성 중 · 미전송',pending:'입금 확인 대기',confirmed:'관리자 입금 확인 완료',returned:'재확인 요청'};
const empty=()=>({id:crypto.randomUUID(),requestId:'',amount:'',paidOn:'',careStart:'',careEnd:'',depositor:'',account:''});
const period=(start?:string,end?:string)=>start&&end?`${start.replaceAll('-', '. ')} - ${end.replaceAll('-', '. ')}`:'기간 미등록';
export default function PaymentNotices({hospitalId}:{hospitalId?:string}){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<ReturnType<typeof empty>|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0),[review,setReview]=useState(false),[stage,setStage]=useState<'editing'|'saved'|'sent'|'checked'>('editing');
 const url='/api/payment-notices'+(hospitalId?'?hospital='+encodeURIComponent(hospitalId):'');
 useEffect(()=>{setForm(empty());},[hospitalId]);
 useEffect(()=>{let live=true,controller:AbortController;async function load(){controller?.abort();controller=new AbortController();try{const response=await fetch(url,{cache:'no-store',signal:controller.signal});const body=await response.json();if(!response.ok){if(live)setData(null);throw Error(body.error||'통보 조회 실패');}if(live){setData(body);setError('');}}catch(e){if(live&&!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'조회 실패');}}load();const timer=setInterval(load,10000);return()=>{live=false;controller?.abort();clearInterval(timer);};},[url,version]);
 async function action(body:Record<string,unknown>){setBusy(true);setMessage('');try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error);setMessage(body.action==='acknowledge'?'통보 접수를 확인했습니다. 실제 은행 입금 확인은 관리자가 별도로 진행합니다.':body.action==='confirm'?'은행 입금 확인을 기록했습니다. 주·월·년 누계에 반영됩니다.':body.action==='return'?'재확인을 요청했습니다.':body.action==='save'?'통보를 저장했습니다. 협회(간병24) 보내기를 눌러 제출해 주세요.':'입금 통보를 보냈습니다. 관리자 확인 후 누계에 반영됩니다.');if(body.action==='save'){setStage('saved');setReview(false);}if(body.action==='send'){setStage('sent');setReview(false);}if(body.action==='acknowledge'){setStage('checked');setReview(true);}setVersion(v=>v+1);}catch(e){setMessage(e instanceof Error?e.message:'처리 실패');}finally{setBusy(false);}}
 const set=(key:string,value:string)=>{setForm(f=>f?{...f,[key]:value}:f);setStage('editing');setReview(false);};
 if(!data||(data.role!=='admin'&&data.role!=='hospital'&&!data.requests.length&&!data.notices.length))return null;
 return <section className={styles.summary} aria-label="간병비 입금 통보"><h2>간병비 입금 통보</h2><p>입금 통보 → 관리자 은행내역 확인 → 입금 확인 완료 → 누적금액 반영</p><p>입금 통보만으로 입금 완료 처리되지 않습니다. 누적금액은 협회(간병24) 관리자와 해당 병원 관계자만 확인합니다. 환자·보호자는 본인 의뢰의 입금 통보만 작성합니다.</p>{error&&<p role="alert">{error}</p>}<p role="status">{message}</p>{data&&<><p>확인 대기 {data.notices.filter(n=>n.status==='pending').length}건 · 확인 완료 {data.notices.filter(n=>n.status==='confirmed').length}건</p>
 {data.summary&&<section aria-label="입금 누적 상황판"><h3>입금 누적 상황판{data.role==='hospital'?' · 소속 병원':''}</h3><p>관리자가 확인한 누적 입금액: <strong>{data.summary.paid.toLocaleString('ko-KR')}원</strong></p><p>누적 환불액: {data.summary.refunded.toLocaleString('ko-KR')}원 · 환불 차감 후: <strong>{data.summary.net.toLocaleString('ko-KR')}원</strong></p><p>확인 대기 통보는 누적금액에 포함되지 않습니다.</p></section>}
 {data.canCreate&&form&&<details><summary>{data.role==='admin'?'관리자: 입금 통보 기록':'환자·보호자: 입금 통보 작성'}</summary><p>환자·보호자가 알려준 입금 내용을 해당 의뢰에 기록하세요. 실제 입금 여부는 은행 거래내역으로 확인해 주세요.</p><form onSubmit={e=>{e.preventDefault();action({...form,amount:Number(form.amount),requestId:Number(form.requestId),action:(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')||'save'});}}><fieldset disabled={busy||stage==='sent'||stage==='checked'} style={{border:0,padding:0,margin:0}}><label>의뢰번호(환자명)<select required value={form.requestId} onChange={e=>set('requestId',e.target.value)}><option value="">의뢰 선택</option>{data.requests.map(r=><option key={r.id} value={r.id}>의뢰 {r.id}번 ({r.patientName})</option>)}</select></label><label>실제 입금일<input type="date" required value={form.paidOn} onChange={e=>set('paidOn',e.target.value)}/></label><fieldset style={{margin:"12px 0",padding:12,border:"1px solid #bdd4ce",borderRadius:8}}><legend>간병기간</legend><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><label>간병 시작일<input type="date" required max={form.careEnd||undefined} value={form.careStart} onChange={e=>set("careStart",e.target.value)}/></label><label>간병 종료일<input type="date" required min={form.careStart||undefined} value={form.careEnd} onChange={e=>set("careEnd",e.target.value)}/></label></div><p>{period(form.careStart,form.careEnd)}</p></fieldset><label>입금 금액(원)<input type="number" min="1" max="1000000000000" step="1" required value={form.amount} onChange={e=>set('amount',e.target.value)}/></label><label>입금자명<input required maxLength={80} value={form.depositor} onChange={e=>set('depositor',e.target.value)} placeholder="은행에 표시된 입금자명"/></label><label>입금한 계좌<select required value={form.account} onChange={e=>set('account',e.target.value)}><option value="">계좌 선택</option>{careDepositAccounts.map(a=><option key={a.account} value={a.account}>{a.bank} {a.account} · {a.holder}</option>)}</select></label></fieldset><p>저장 → 통보(보내기) → 확인</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button value="save" disabled={busy||stage==='sent'||stage==='checked'}>저장</button><button value="send" disabled={busy||stage!=='saved'}>협회(간병24) 통보(보내기)</button><button type="button" disabled={busy||stage!=='sent'} onClick={()=>action({id:form.id,action:"acknowledge"})}>확인</button>{stage==='checked'&&<button type="button" onClick={()=>{setForm(empty());setStage("editing");setReview(false);}}>다음 입금 작성</button>}</div>{review&&<p>의뢰 {form.requestId||'미선택'}번 ({data.requests.find(r=>String(r.id)===form.requestId)?.patientName||'환자 미선택'}) · {form.paidOn||'날짜 미입력'} · {Number(form.amount||0).toLocaleString('ko-KR')}원 · {form.depositor||'입금자 미입력'} · {form.account||'계좌 미선택'}<br/>간병기간: {period(form.careStart,form.careEnd)}<br/>통보 접수를 확인했습니다. 은행 입금 확인 완료를 뜻하지 않습니다.</p>}</form></details>}
 <h3>입금 통보 내역</h3>{!data.notices.length&&<p>표시할 입금 통보가 없습니다.</p>}{data.notices.map(n=><article key={n.id} style={{background:'white',border:'1px solid #bdd4ce',borderRadius:10,padding:16,margin:'12px 0'}}><h3>의뢰 {n.requestId}번 ({n.patientName}) · {labels[n.status]||n.status}</h3>{data.role!=='hospital'&&<p>{n.paidOn} · {Number(n.amount||0).toLocaleString('ko-KR')}원 · 입금자 {n.depositor}<br/>간병기간: {period(n.careStart,n.careEnd)}<br/>우리은행 {n.account}</p>}{n.reason&&<p>재확인 사유: {n.reason}</p>}{n.confirmedAt&&<p>관리자 확인일: {new Date(n.confirmedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>}{n.canAcknowledge&&!n.canEdit&&<button type="button" disabled={busy} onClick={()=>{setForm({id:n.id,requestId:String(n.requestId),amount:String(n.amount),paidOn:n.paidOn||'',careStart:n.careStart||'',careEnd:n.careEnd||'',depositor:n.depositor||'',account:n.account||''});setStage('sent');setReview(false);}}>보낸 통보 불러오기</button>}{n.canEdit&&<button type="button" disabled={busy} onClick={()=>{setForm({id:n.id,requestId:String(n.requestId),amount:String(n.amount),paidOn:n.paidOn||'',careStart:n.careStart||'',careEnd:n.careEnd||'',depositor:n.depositor||'',account:n.account||''});setStage('saved');setReview(false);setMessage('위의 입금 통보 작성 항목을 열어 수정 후 보내세요.');}}>불러와 수정</button>}
 {data.role==='admin'&&n.status==='pending'&&<><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action({id:n.id,action:'confirm',reference:f.get('reference'),confirmedAmount:Number(f.get('confirmedAmount')),bankChecked:f.get('bankChecked')==='on'});}}><label>은행에서 확인한 실제 금액<input type="number" name="confirmedAmount" min="1" step="1" required/></label><label>은행 거래번호<input name="reference" maxLength={100} required placeholder="기존 입금 장부와 동일한 거래번호 사용"/></label><label><input type="checkbox" name="bankChecked" required/>입금일·입금자·계좌·금액을 실제 은행 거래내역과 대조했습니다.</label><button disabled={busy}>관리자 입금 확인</button></form><form onSubmit={e=>{e.preventDefault();action({id:n.id,action:'return',reason:new FormData(e.currentTarget).get('reason')});}}><label>재확인 사유<select name="reason" required>{['은행 내역 미확인','입금일·금액 확인 필요','입금자·계좌 확인 필요','중복 통보'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy}>재확인 요청</button></form></>}
 </article>)}</>}</section>;
}
