import {profileNotice} from '@/lib/notification-events';
import {withActor,scope,scopedId,ownership,workflowGuard,type Actor} from "../../../lib/auth";
import{desc,eq}from"drizzle-orm";import{getDb}from"../../../db";import{applications}from"../../../db/schema";
const required=["applicantName","applicantPhone","applicantBirth","applicantGender","careerYears","preferredDate","caregiverHandwriting"] as const;
function valid(b:Record<string,any>){return required.every(k=>String(b[k]||"").trim())}
function values(b:Record<string,any>){const sent=b.action==="send";return{applicantName:b.applicantName,applicantPhone:b.applicantPhone,applicantBirth:b.applicantBirth,applicantGender:b.applicantGender,careerYears:b.careerYears,qualification:b.qualification||"",preferredDate:b.preferredDate,applicationNote:b.applicationNote||"",caregiverHandwriting:b.caregiverHandwriting||"",status:sent?"sent":"saved",sentTargets:sent?"협회 · 간병24":""}}
async function handleGET(req:Request, actor:Actor){try{return Response.json({applications:await getDb().select().from(applications).where(scope(applications,actor)).orderBy(desc(applications.id)).limit(100)})}catch{return Response.json({error:"신청 접수함을 불러올 수 없습니다."},{status:500})}}
async function handlePOST(req:Request, actor:Actor){try{const b=await req.json() as Record<string,any>;if(!valid(b))return Response.json({error:"간병인 신청서의 필수 항목과 자필 서명을 확인해주세요."},{status:400});const[x]=await getDb().insert(applications).values({...values(b),providerContractVersion:"",...ownership(actor)}).returning();const notification=await profileNotice(x,b);return Response.json({application:x,notification},{status:201})}catch{return Response.json({error:"신청서 저장 중 문제가 발생했습니다."},{status:500})}}
async function handlePATCH(req:Request, actor:Actor){try{const b=await req.json() as Record<string,any>,id=Number(b.id);if(!id||!valid(b))return Response.json({error:"간병인 신청서의 필수 항목과 자필 서명을 확인해주세요."},{status:400});const[x]=await getDb().update(applications).set(values(b)).where(scopedId(applications,id,actor)).returning();const notification=x?await profileNotice(x,b):undefined;return x?Response.json({application:x,notification}):Response.json({error:"신청서를 찾을 수 없습니다."},{status:404})}catch{return Response.json({error:"신청서 처리 중 문제가 발생했습니다."},{status:500})}}

export const GET=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handleGET(req,actor);});
export const POST=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePOST(req,actor);});
export const PATCH=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePATCH(req,actor);});
