"use client";
import {useEffect,useState} from 'react';
type Row={id:string;caregiver_name:string;hospital_name:string;status:string;association_approved_by:string|null;hospital_approved_by:string|null;created_at:number};
const labels:Record<string,string>={pending:'승인 대기',registered:'등록 완료',reject:'반려',revoke:'등록 해제',withdraw:'신청 철회',account_inactive:'계정 이용 중지'};
export default function HospitalRegistration(){
 const[rows,setRows]=useState<Row[]>([]),[hospitals,setHospitals]=useState<{id:string;name:string}[]>([]),[role,setRole]=useState(''),[hospitalId,setHospitalId]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 async function load(){const r=await fetch('/api/hospital-registrations',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'목록을 불러오지 못했습니다.');setRows(d.registrations);setHospitals(d.hospitals);const params=new URLSearchParams(window.location.search);const selected=d.hospitals.find((h:{id:string;name:string})=>h.id===params.get('hospital'))||d.hospitals.find((h:{id:string;name:string})=>h.name===params.get('name'));if(selected)setHospitalId(selected.id);setRole(d.role);setReady(true);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function send(action:string,id?:string){setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/hospital-registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,hospitalId})});const d=await r.json();if(!r.ok)throw Error(d.error||'처리하지 못했습니다.');await load();setMessage(action==='apply'?'신청을 보냈습니다. 협회(간병24 포함)와 병원 병실 담당간호사의 승인을 기다려 주세요.':action==='approve'?'승인을 저장했습니다. 두 담당자가 모두 승인하면 등록 완료로 표시됩니다.':'처리를 완료했습니다.');if(action==='apply')setHospitalId('');}catch(e){setError(e instanceof Error?e.message:'처리 실패');}finally{setBusy(false);}}
 return <main style={{maxWidth:900,margin:'24px auto',padding:20}}><h1>병원별 간병인 등록</h1><p>해당 병원 '간병 의뢰' 상황판 보고 '간병 신청' → 협회(간병24 포함) 승인 + 병동 병실 담당간호사 승인(필수서류제출) → 등록 및 매칭 완료 → 작업복 착용 후 업무 시작</p><p>승인 순서는 상관없으며, 협회(간병24 포함)와 해당 병원 병실 담당간호사 모두 승인해야 등록됩니다. 병원별 등록은 개별 간병 의뢰의 매칭·계약과 별도로 진행됩니다.</p><section className="auth-card"><h2>등록 후 근무 안내</h2><p><strong>병원 등록을 마친 간병인은 협회(간병24 포함)에서 증명서를 발급받아 패찰하고 근무합니다.</strong></p><p>등록 완료 후 협회에 증명서 발급을 요청하고, 근무 시 증명서를 패찰해 주세요.</p></section><a href="/hospitals">전국 병원 찾기</a>{error&&<p role="alert">{error}</p>}{message&&<section className="auth-card" role="status"><strong>{message}</strong><button type="button" onClick={()=>setMessage('')}>확인</button></section>}
 {!ready&&!error&&<p>등록 현황을 불러오는 중…</p>}
 {role==='caregiver'&&<form className="auth-card" onSubmit={e=>{e.preventDefault();send('apply');}}><h2>병원 등록 신청</h2><label>희망 병원<select required value={hospitalId} onChange={e=>setHospitalId(e.target.value)}><option value="">병원을 선택하세요</option>{hospitals.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></label><p>목록에 없는 병원은 협회(간병24 포함)에 병원 등록을 요청해 주세요. 전화 1600-5197</p><button disabled={busy||!hospitalId}>신청 보내기</button></form>}
 {role==='admin'&&<p><a href="/admin">병원·병실 담당간호사 계정 관리</a>에서 병원을 추가하고 병실 담당간호사의 계정에 해당 병원 소속과 병원 담당자 권한을 지정해 주세요. 이 등록제의 병원 승인은 해당 계정으로 처리합니다.</p>}
 <h2>{role==='caregiver'?'내 신청·등록 현황':'간병인 신청·등록 현황'}</h2>{ready&&!rows.length&&<p>아직 신청된 내역이 없습니다.</p>}
 {rows.map(r=><section className="auth-card" key={r.id}><h3>{r.hospital_name}</h3><p>간병인: {r.caregiver_name}</p><strong>{labels[r.status]||r.status}</strong>{r.status==='registered'&&<p><strong>근무 전: 협회(간병24 포함)에서 증명서 발급 → 패찰 후 근무</strong></p>}<p>협회(간병24 포함): {r.association_approved_by?'승인 완료':'승인 대기'} · 병원 병실 담당간호사: {r.hospital_approved_by?'승인 완료':'승인 대기'}</p><p>신청일 {new Date(r.created_at).toLocaleDateString('ko-KR')}</p>{['pending','registered'].includes(r.status)&&<div style={{display:'flex',gap:12,flexWrap:'wrap'}}>{role==='caregiver'?<button disabled={busy} onClick={()=>{if(confirm('이 병원 등록 신청을 철회하시겠습니까?'))send('withdraw',r.id);}}>신청 철회</button>:<>{r.status==='pending'&&!(role==='admin'?r.association_approved_by:r.hospital_approved_by)&&<button disabled={busy} onClick={()=>send('approve',r.id)}>{role==='admin'?'협회(간병24 포함) 승인':'병실 담당간호사 승인'}</button>}<button disabled={busy} onClick={()=>{const action=r.status==='registered'?'revoke':'reject';if(confirm(action==='revoke'?'병원 등록을 해제하시겠습니까?':'신청을 반려하시겠습니까?'))send(action,r.id);}}>{r.status==='registered'?'등록 해제':'반려'}</button></>}</div>}</section>)}
 </main>;
}
