import {createHmac,randomBytes,createHash} from 'node:crypto';
import {encryptText,decryptText} from './data-crypto.mjs';
export const noticeLabels={request:'간병 의뢰 접수',profile:'간병인 신청서 접수',application:'간병 신청 접수',selected:'간병인 선정',matched:'계약·근무 일정 안내',test:'자동 알림 연결 확인'};
export const phone=value=>{const p=String(value||'').replace(/[^0-9]/g,'');return /^01[016789][0-9]{7,8}$/.test(p)?p:''};
export function managerPhones(value){const values=String(value||'').split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);if(!values.length||values.length>5||values.some(x=>!phone(x)))throw Error('수신번호를 쉼표로 구분해 최대 5개 입력하세요.');return [...new Set(values.map(phone))];}
export async function ensureNotifications(db){await db.execute('CREATE TABLE IF NOT EXISTS notification_settings(id INTEGER PRIMARY KEY,payload TEXT NOT NULL)');await db.execute('CREATE TABLE IF NOT EXISTS notification_preferences(entity TEXT PRIMARY KEY,enabled INTEGER NOT NULL)');await db.execute('CREATE TABLE IF NOT EXISTS notification_outbox(event_key TEXT PRIMARY KEY,kind TEXT NOT NULL,recipient TEXT NOT NULL,state TEXT NOT NULL,payload TEXT NOT NULL,provider_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)');}
export async function notificationSettings(db){await ensureNotifications(db);const r=await db.execute('SELECT payload FROM notification_settings WHERE id=1');return r.rows.length?JSON.parse(decryptText(r.rows[0].payload,'notification.settings')):{};}
export async function saveNotificationSettings(db,body){const old=await notificationSettings(db);const c={enabled:body.enabled===true,participants:body.participants===true,from:phone(body.from),manager:managerPhones(body.manager).join(','),apiKey:String(body.apiKey||old.apiKey||''),apiSecret:String(body.apiSecret||old.apiSecret||'')};if(!c.from||!c.manager)throw Error('발신번호와 담당자 휴대전화번호를 확인하세요.');if(c.enabled&&(!c.apiKey||!c.apiSecret))throw Error('API 키와 비밀값을 등록하세요.');if(!/^[A-Za-z0-9]*$/.test(c.apiKey)||! /^[A-Za-z0-9]*$/.test(c.apiSecret))throw Error('API 키 형식을 확인하세요.');await db.execute({sql:'INSERT INTO notification_settings(id,payload) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload',args:[encryptText(JSON.stringify(c),'notification.settings')]});}
export async function saveNoticePreference(db,entity,enabled){await ensureNotifications(db);await db.execute({sql:'INSERT INTO notification_preferences(entity,enabled) VALUES(?,?) ON CONFLICT(entity) DO UPDATE SET enabled=excluded.enabled',args:[entity,enabled===true?1:0]});}
export async function wantsNotice(db,entity){await ensureNotifications(db);const r=await db.execute({sql:'SELECT enabled FROM notification_preferences WHERE entity=?',args:[entity]});return Number(r.rows[0]?.enabled)===1;}
export function noticeText(kind){if(!noticeLabels[kind])throw Error('알림 종류 오류');return `[간병24] ${noticeLabels[kind]} 안내가 있습니다. 앱에 로그인하여 확인해 주세요. https://care.xn--24-ts1i486c.com/`;}
export async function solapiSend(c,to,kind,transport=fetch){const date=new Date().toISOString(),salt=randomBytes(16).toString('hex'),signature=createHmac('sha256',c.apiSecret).update(date+salt).digest('hex');const r=await transport('https://api.solapi.com/messages/v4/send-many/detail',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`HMAC-SHA256 apiKey=${c.apiKey}, date=${date}, salt=${salt}, signature=${signature}`},body:JSON.stringify({messages:[{to,from:c.from,text:noticeText(kind),type:'LMS',subject:'간병24 업무 알림'}],allowDuplicates:false}),signal:AbortSignal.timeout(10000)});const d=await r.json();if(!r.ok)return {state:'failed',providerId:null};if((d.failedMessageList||[]).length||Number(d.groupInfo?.count?.registeredFailed)>0)return {state:'failed',providerId:d.groupInfo?.groupId||null};return d.groupInfo?.groupId?{state:'accepted',providerId:d.groupInfo.groupId}:{state:'unknown',providerId:null};}
export async function notifyEvent(db,event,kind,recipients=[],transport=fetch){try{const c=await notificationSettings(db);if(!c.enabled)return {state:'disabled'};const targets=[...managerPhones(c.manager).map(p=>({phone:p,role:'manager'})),...(c.participants?recipients:[])];const seen=new Set();const results=[];for(const target of targets){const to=phone(target.phone);if(!to||seen.has(to))continue;seen.add(to);const key=event+':'+createHash('sha256').update(to).digest('hex');const stamp=new Date().toISOString();const claim=await db.execute({sql:'INSERT OR IGNORE INTO notification_outbox(event_key,kind,recipient,state,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',args:[key,kind,target.role,'sending',encryptText(to,'notification.'+key),stamp,stamp]});if(!claim.rowsAffected){results.push('duplicate');continue;}let result;try{result=await solapiSend(c,to,kind,transport);}catch{result={state:'unknown',providerId:null};}await db.execute({sql:'UPDATE notification_outbox SET state=?,provider_id=?,updated_at=? WHERE event_key=?',args:[result.state,result.providerId,new Date().toISOString(),key]});results.push(result.state);}return {state:results.some(x=>x==='failed'||x==='unknown')?'attention':'accepted'};}catch{return {state:'attention'};}}
