import {encryptText} from '../lib/data-crypto.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createClient} from '@libsql/client';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {changeNotice,listNotices,ensureNotices} from '../lib/payment-notices.mjs';import {recordPayment} from '../lib/contribution-ledger.mjs';import {monthlySummary,totals} from '../lib/monthly-contribution.mjs';
test('payment notices enforce ownership, hospital status-only access, review and exactly-once ledger posting',async()=>{const folder=await mkdtemp(join(tmpdir(),'care24-notices-')),before=process.env.CARE24_KEY_FILE;process.env.CARE24_KEY_FILE=join(folder,'key.json');await writeFile(process.env.CARE24_KEY_FILE,JSON.stringify({active:'test',keys:{test:Buffer.alloc(32,9).toString('base64')}}));const db=createClient({url:':memory:'});const owner={id:'owner',role:'caregiver'},stranger={id:'other',role:'caregiver'},admin={id:'admin',role:'admin'},staff={id:'staff',role:'hospital',hospitalId:'A'},otherStaff={id:'staffb',role:'hospital',hospitalId:'B'};try{
await db.execute('CREATE TABLE care_requests(id INTEGER PRIMARY KEY,hospital_id TEXT,owner_user_id TEXT,patient_name TEXT)');await db.execute("INSERT INTO care_requests VALUES(1,'A','owner',''),(2,'B','other','')");await db.execute({sql:'UPDATE care_requests SET patient_name=? WHERE id=1',args:[encryptText('홍길동','care_requests.patient_name')]});await ensureNotices(db);assert.equal((await listNotices(db,admin)).requests[0].patientName,'홍길동');assert.equal((await listNotices(db,owner)).requests[0].patientName,'홍○동');
const input={id:randomUUID(),requestId:1,amount:700000,paidOn:'2026-09-01',careStart:'2026-09-01',careEnd:'2026-09-07',depositor:'시험입금자',account:'1005-304-803945',action:'save'};
await assert.rejects(()=>changeNotice(db,stranger,input),/본인이/);await assert.rejects(()=>changeNotice(db,owner,{...input,account:'123456789'}),/계좌/);await assert.rejects(()=>changeNotice(db,owner,{...input,careStart:''}),/간병 시작일/);await assert.rejects(()=>changeNotice(db,owner,{...input,careEnd:'2026-08-31'}),/간병 시작일/);await assert.rejects(()=>changeNotice(db,owner,{...input,careStart:'2026-02-30'}),/간병 시작일/);await assert.rejects(()=>changeNotice(db,owner,{...input,action:'send'}),/먼저 저장/);await changeNotice(db,owner,input);assert.equal((await listNotices(db,owner)).notices[0].careStart,'2026-09-01');assert.equal((await listNotices(db,owner)).notices[0].careEnd,'2026-09-07');assert.equal((await listNotices(db,admin)).notices.length,0);assert.equal((await listNotices(db,staff)).notices.length,0);const raw=(await db.execute('SELECT payload FROM care_payment_notices')).rows[0].payload;assert(raw.startsWith('care24enc:v1:'));assert(!raw.includes('시험입금자'));
await assert.rejects(()=>changeNotice(db,owner,{...input,amount:800000,action:'send'}),/먼저 저장/);await changeNotice(db,owner,{...input,action:'send'});await changeNotice(db,owner,{id:input.id,action:'acknowledge'});assert.equal((await listNotices(db,staff)).summary.paid,0);assert.equal((await listNotices(db,owner)).summary,undefined);assert.equal((await db.execute('SELECT COUNT(*) AS n FROM care_payments')).rows[0].n,0);assert.equal((await listNotices(db,stranger)).notices.length,0);assert.equal((await listNotices(db,otherStaff)).notices.length,0);const staffNotice=(await listNotices(db,staff)).notices[0];for(const key of ['amount','depositor','account','payload','payment_id','careStart','careEnd'])assert.equal(staffNotice[key],undefined);assert.equal(staffNotice.status,'pending');assert.equal(staffNotice.patientName,'홍○동');assert.equal((await listNotices(db,admin)).notices[0].patientName,'홍길동');assert.equal((await listNotices(db,owner)).notices[0].patientName,'홍○동');assert.equal((await listNotices(db,{...admin,contextHospitalId:'B'})).notices.length,0);
await assert.rejects(()=>changeNotice(db,owner,{id:input.id,action:'confirm',reference:'bank1',confirmedAmount:700000,bankChecked:true}),/관리자/);
await assert.rejects(()=>changeNotice(db,admin,{id:input.id,action:'confirm',reference:'bank1',confirmedAmount:600000,bankChecked:true}),/금액/);assert.equal((await db.execute('SELECT COUNT(*) AS n FROM care_payments')).rows[0].n,0);
await changeNotice(db,admin,{id:input.id,action:'return',reason:'입금일·금액 확인 필요'});await changeNotice(db,owner,input);await changeNotice(db,owner,{...input,action:'send'});const confirm={id:input.id,action:'confirm',reference:'bank1',confirmedAmount:700000,bankChecked:true};await changeNotice(db,admin,confirm);await changeNotice(db,admin,confirm);assert.equal((await db.execute('SELECT COUNT(*) AS n FROM care_payments')).rows[0].n,1);assert.equal((await listNotices(db,owner)).notices[0].status,'confirmed');assert.equal((await listNotices(db,staff)).notices[0].status,'confirmed');assert.equal((await listNotices(db,staff)).summary.paid,700000);assert.equal((await listNotices(db,otherStaff)).summary.paid,0);await assert.rejects(()=>changeNotice(db,staff,{id:input.id,action:'acknowledge'}),/본인 통보/);await assert.rejects(()=>changeNotice(db,stranger,{id:input.id,action:'acknowledge'}),/본인 통보/);assert.equal(totals(monthlySummary((await db.execute('SELECT * FROM care_payments')).rows)).contribution,7000);
const duplicate={...input,id:randomUUID(),action:'send'};await changeNotice(db,owner,{...duplicate,action:"save"});await changeNotice(db,owner,duplicate);await assert.rejects(()=>changeNotice(db,admin,{...confirm,id:duplicate.id}),/이미 사용/);assert.equal((await db.execute('SELECT COUNT(*) AS n FROM care_payments')).rows[0].n,1);
await recordPayment(db,{hospitalId:'A',kind:'payment',reference:'manual-existing',paidOn:'2026-09-01',amount:700000},'admin');await changeNotice(db,admin,{...confirm,id:duplicate.id,reference:'manual-existing'});assert.equal((await db.execute('SELECT COUNT(*) AS n FROM care_payments')).rows[0].n,2);
}finally{db.close();if(before)process.env.CARE24_KEY_FILE=before;else delete process.env.CARE24_KEY_FILE;assert(resolve(folder).startsWith(resolve(tmpdir())+'\\care24-notices-')||resolve(folder).startsWith(resolve(tmpdir())+'/care24-notices-'));await rm(folder,{recursive:true,force:true});}});
