import {maskPatientName} from './admin-privacy.mjs';
import {randomUUID} from 'node:crypto';
import {encryptText,decryptText} from './data-crypto.mjs';
import {ensureLedger} from './contribution-ledger.mjs';
import {koreaToday} from './monthly-contribution.mjs';
import {careDepositAccounts} from './care-deposit-accounts.mjs';
export async function ensureNotices(db){await ensureLedger(db);await db.execute(`CREATE TABLE IF NOT EXISTS care_payment_notices(id TEXT PRIMARY KEY,request_id INTEGER NOT NULL,hospital_id TEXT NOT NULL,owner_id TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL,reason TEXT NOT NULL DEFAULT '',payment_id TEXT UNIQUE,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,confirmed_by TEXT,confirmed_at TEXT)`);}
function allowedRequest(actor,r){if(!r||!r.hospital_id||(actor.contextHospitalId&&actor.contextHospitalId!==r.hospital_id))return false;return actor.role==='admin'||(actor.role!=='hospital'&&r.owner_user_id===actor.id);}
export function canSeeNotice(actor,n){if(actor.contextHospitalId&&n.hospital_id!==actor.contextHospitalId)return false;if(actor.role==='admin')return n.status!=='draft'||n.owner_id===actor.id;if(actor.role==='hospital')return !!actor.hospitalId&&actor.hospitalId===n.hospital_id&&n.status!=='draft';return n.request_owner===actor.id&&n.owner_id===actor.id;}
function patientName(actor,value){const name=value?decryptText(value,'care_requests.patient_name'):'';return name?(actor.role==='admin'?name:maskPatientName(name)):'성명 미등록';}
export function noticeView(actor,n){const result={id:n.id,requestId:Number(n.request_id),patientName:patientName(actor,n.patient_name),hospitalId:n.hospital_id,status:n.status,reason:n.reason,updatedAt:n.updated_at,confirmedAt:n.confirmed_at};if(actor.role==='hospital')return result;return {...result,canAcknowledge:n.owner_id===actor.id,canEdit:n.owner_id===actor.id&&['draft','returned'].includes(n.status),...JSON.parse(decryptText(n.payload,'payment-notice.'+n.id))};}
export async function listNotices(db,actor){await ensureNotices(db);const requests=(await db.execute('SELECT id,hospital_id,owner_user_id,patient_name FROM care_requests')).rows;const rows=(await db.execute('SELECT n.*,r.owner_user_id AS request_owner,r.patient_name FROM care_payment_notices n JOIN care_requests r ON r.id=n.request_id ORDER BY n.updated_at DESC')).rows.filter(n=>canSeeNotice(actor,n));let summary; if(actor.role==='admin'||(actor.role==='hospital'&&actor.hospitalId&&(!actor.contextHospitalId||actor.contextHospitalId===actor.hospitalId))){const scope=actor.role==='hospital'?actor.hospitalId:actor.contextHospitalId;const sums=(await db.execute({sql:"SELECT COALESCE(SUM(CASE WHEN kind='payment' THEN amount ELSE 0 END),0) AS paid,COALESCE(SUM(CASE WHEN kind='refund' THEN amount ELSE 0 END),0) AS refunded FROM care_payments"+(scope?' WHERE hospital_id=?':''),args:scope?[scope]:[]})).rows[0];summary={paid:Number(sums.paid),refunded:Number(sums.refunded),net:Number(sums.paid)-Number(sums.refunded)};}return {summary,role:actor.role,canCreate:actor.role!=='hospital',requests:actor.role==='hospital'?[]:requests.filter(r=>allowedRequest(actor,r)).map(r=>({id:Number(r.id),hospitalId:r.hospital_id,patientName:patientName(actor,r.patient_name)})),notices:rows.map(n=>noticeView(actor,n))};}
export async function changeNotice(db,actor,input){await ensureNotices(db);const tx=await db.transaction('write');try{const id=String(input.id||''),action=String(input.action||'');if(!/^[a-f0-9-]{36}$/.test(id))throw Error('통보 번호를 확인하세요.');const existing=(await tx.execute({sql:'SELECT n.*,r.owner_user_id AS request_owner FROM care_payment_notices n JOIN care_requests r ON r.id=n.request_id WHERE n.id=?',args:[id]})).rows[0];
 if(action==='acknowledge'){if(!existing||actor.role==='hospital'||existing.owner_id!==actor.id||!canSeeNotice(actor,existing)||!['pending','confirmed','returned'].includes(existing.status))throw Error('보낸 본인 통보만 확인할 수 있습니다.');const p=JSON.parse(decryptText(existing.payload,'payment-notice.'+id));p.receiptCheckedAt=p.receiptCheckedAt||new Date().toISOString();await tx.execute({sql:'UPDATE care_payment_notices SET payload=? WHERE id=?',args:[encryptText(JSON.stringify(p),'payment-notice.'+id),id]});await tx.commit();return{id,status:existing.status,receiptCheckedAt:p.receiptCheckedAt};}
 if(action==='save'||action==='send'){
  if(actor.role==='hospital')throw Error('병원 담당자는 통보 상태만 조회할 수 있습니다.');
  const requestId=Number(input.requestId),r=(await tx.execute({sql:'SELECT id,hospital_id,owner_user_id FROM care_requests WHERE id=?',args:[requestId]})).rows[0];if(!allowedRequest(actor,r))throw Error('본인이 작성한 의뢰를 선택하세요.');if(existing&&(existing.request_id!==requestId||existing.hospital_id!==r.hospital_id||existing.owner_id!==actor.id))throw Error('다른 사람의 통보를 변경할 수 없습니다.');if(existing&&!['draft','returned'].includes(existing.status)){if(action==='send'&&existing.status==='pending'){await tx.commit();return{id,status:'pending'};}throw Error('이미 보낸 통보는 수정할 수 없습니다.');}
  const amount=Number(input.amount),paidOn=String(input.paidOn||''),depositor=String(input.depositor||'').trim(),account=String(input.account||'');if(!Number.isSafeInteger(amount)||amount<1||amount>1e12||!depositor||depositor.length>80||!careDepositAccounts.some(a=>a.account===account))throw Error('입금액·입금자명·입금한 계좌를 확인하세요.');if(!/^\d{4}-\d{2}-\d{2}$/.test(paidOn)||Number.isNaN(Date.parse(paidOn))||new Date(paidOn).toISOString().slice(0,10)!==paidOn||paidOn>koreaToday())throw Error('실제 입금일을 입력하세요.');
  const careStart=String(input.careStart||''),careEnd=String(input.careEnd||'');const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;if(!validDate(careStart)||!validDate(careEnd)||careEnd<careStart)throw Error('간병 시작일과 종료일을 확인하세요. 종료일은 시작일보다 빠를 수 없습니다.');
  if(action==='send'){if(!existing||existing.status!=='draft')throw Error('먼저 저장한 뒤 통보(보내기)를 진행하세요.');const saved=JSON.parse(decryptText(existing.payload,'payment-notice.'+id));const next={amount,paidOn,depositor,account,careStart,careEnd};if(Object.keys(next).some(key=>saved[key]!==next[key]))throw Error('변경한 내용을 먼저 저장해 주세요.');}
  const payload=encryptText(JSON.stringify({amount,paidOn,depositor,account,careStart,careEnd}),'payment-notice.'+id),status=action==='save'?'draft':'pending',now=new Date().toISOString();if(existing)await tx.execute({sql:'UPDATE care_payment_notices SET payload=?,status=?,reason=?,updated_at=? WHERE id=?',args:[payload,status,'',now,id]});else await tx.execute({sql:'INSERT INTO care_payment_notices(id,request_id,hospital_id,owner_id,payload,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',args:[id,requestId,r.hospital_id,actor.id,payload,status,now,now]});await tx.commit();return{id,status};
 }
 if(actor.role!=='admin'||!existing||!canSeeNotice(actor,existing))throw Error('관리자만 입금을 확인할 수 있습니다.');if(action==='confirm'&&existing.status==='confirmed'){await tx.commit();return{id,status:'confirmed'};}if(existing.status!=='pending')throw Error('확인 대기 중인 통보를 선택하세요.');const now=new Date().toISOString();
 if(action==='return'){if(!['은행 내역 미확인','입금일·금액 확인 필요','입금자·계좌 확인 필요','중복 통보'].includes(input.reason))throw Error('재확인 사유를 선택하세요.');await tx.execute({sql:"UPDATE care_payment_notices SET status='returned',reason=?,updated_at=? WHERE id=?",args:[input.reason,now,id]});await tx.commit();return{id,status:'returned'};}
 if(action!=='confirm'||input.bankChecked!==true)throw Error('실제 은행 거래내역 확인이 필요합니다.');const reference=String(input.reference||'').trim();if(!reference||reference.length>100)throw Error('은행 거래번호를 입력하세요.');const p=JSON.parse(decryptText(existing.payload,'payment-notice.'+id));if(Number(input.confirmedAmount)!==p.amount)throw Error('은행에서 확인한 금액과 통보 금액이 다릅니다. 재확인을 요청하세요.');
 const found=(await tx.execute({sql:'SELECT * FROM care_payments WHERE reference=?',args:[reference]})).rows[0];let paymentId=found?.id||randomUUID();if(found){const linked=(await tx.execute({sql:'SELECT id FROM care_payment_notices WHERE payment_id=?',args:[found.id]})).rows;if(linked.length||found.kind!=='payment'||found.hospital_id!==existing.hospital_id||Number(found.amount)!==p.amount||found.paid_on!==p.paidOn)throw Error('이미 사용된 거래번호입니다. 중복 입금을 확인하세요.');}else await tx.execute({sql:"INSERT INTO care_payments(id,reference,kind,amount,payment_id,paid_on,actor_id,created_at,hospital_id) VALUES(?,?,'payment',?,NULL,?,?,?,?)",args:[paymentId,reference,p.amount,p.paidOn,actor.id,now,existing.hospital_id]});
 await tx.execute({sql:"UPDATE care_payment_notices SET status='confirmed',payment_id=?,confirmed_by=?,confirmed_at=?,updated_at=? WHERE id=?",args:[paymentId,actor.id,now,now,id]});await tx.commit();return{id,status:'confirmed'};
 }catch(e){await tx.rollback();throw e;}finally{tx.close();}}
