plugins { id 'com.android.application' }

android {
    namespace 'kr.or.care24.v2'
    compileSdk 36
    defaultConfig {
        applicationId 'kr.or.care24.v2'
        minSdk 26
        targetSdk 36
        versionCode 20002
        versionName '2.0.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes { release { minifyEnabled false } }
}

dependencies { implementation 'androidx.browser:browser:1.10.0' }
