import test from 'node:test';import assert from 'node:assert/strict';import {emptyWorkflow,transition,diaryForActor} from '../lib/care-workflow.mjs';
const actor={id:3,role:'caregiver'},other={id:4,role:'caregiver'},admin={id:1,role:'admin'},now=new Date('2030-01-02T09:00:00Z');
const ready=()=>({...emptyWorkflow(),applications:[{profileId:10,ownerId:3,name:'시험간병인'}],selected:10,startedAt:'2030-01-02T08:00:00Z'});
const body={action:'save_diary',condition:'안정',care:'이동 보조',notes:'다음 담당자 인계'};
test('시작 전, 미래 시작 기록, 다른 간병인, 관리자 대리 작성 차단',()=>{for(const startedAt of ['', '2030-01-03T08:00:00Z'])assert.throws(()=>transition({...ready(),startedAt},body,actor,{},now),/시작/);for(const a of [other,admin])assert.throws(()=>transition(ready(),body,a,{},now),/담당 간병인/)});
test('일지 시각과 작성자는 서버 기록, 기존 기록 유지',()=>{const w=ready();transition(w,{...body,authorId:9,recordedAt:'2000-01-01'},actor,{},now);transition(w,{...body,care:'두 번째 기록'},actor,{},now);assert.equal(w.diary.length,2);assert.equal(w.diary[0].recordedAt,now.toISOString());assert.equal(w.diary[0].authorId,3);assert.equal(w.diary[0].care,'이동 보조');assert.equal(w.diary[1].id,2)});
test('일지 조회는 담당 간병인과 관리자만, 필수값과 길이 검증',()=>{const w=ready();transition(w,body,actor,{},now);assert.equal(diaryForActor(w,actor).length,1);assert.equal(diaryForActor(w,admin).length,1);assert.equal(diaryForActor(w,other),undefined);assert.equal(diaryForActor(w,{id:2,role:'hospital'}),undefined);assert.throws(()=>transition(w,{...body,condition:''},actor,{},now));assert.throws(()=>transition(w,{...body,care:'x'.repeat(4001)},actor,{},now));assert.equal(w.diary.length,1)});
test('협회 관리자만 일지 확인 및 지시, 담당 간병인만 읽음 확인',()=>{const w=ready();transition(w,body,actor,{},now);const review={action:'review_diary',diaryId:1};assert.throws(()=>transition(w,review,actor,{},now),/관리자/);transition(w,review,{...admin,name:'시험관리자'},{},now);assert.equal(w.diary[0].reviewerId,1);const instruction={action:'instruct_diary',diaryId:1,content:'인계 내용을 보완해 주세요.'};assert.throws(()=>transition(w,instruction,other,{},now));transition(w,instruction,{...admin,name:'시험관리자'},{},now);assert.equal(w.diary[0].instructions[0].authorId,1);assert.equal(w.diary[0].instructions[0].acknowledgedAt,'');const ack={action:'ack_instruction',diaryId:1,instructionId:1};assert.throws(()=>transition(w,ack,other,{},now));assert.throws(()=>transition(w,ack,admin,{},now));transition(w,ack,actor,{},now);assert.equal(w.diary[0].instructions[0].acknowledgedBy,3);assert.throws(()=>transition(w,ack,actor,{},now),/이미/);assert.equal(diaryForActor(w,other),undefined)});
test('잘못된 일지와 빈 지시 차단, 추가 지시는 기존 기록 보존',()=>{const w=ready();transition(w,body,actor,{},now);assert.throws(()=>transition(w,{action:'review_diary',diaryId:99},admin,{},now));assert.throws(()=>transition(w,{action:'instruct_diary',diaryId:1,content:' '},admin,{},now));assert.equal(w.diary[0].reviewedAt,undefined);for(const content of ['첫 지시','추가 지시'])transition(w,{action:'instruct_diary',diaryId:1,content},admin,{},now);assert.equal(w.diary[0].instructions.length,2);assert.equal(w.diary[0].instructions[0].content,'첫 지시');assert.equal(w.diary[0].care,'이동 보조');assert.equal(w.diary[0].reviewedAt,now.toISOString())});
