import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,mkdirSync,readdirSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {createClient} from '@libsql/client';
import {encryptBytes,decryptBytes,encryptText,decryptText,prefix} from '../lib/data-crypto.mjs';
import {protectedFields} from '../lib/protected-fields.mjs';
mkdirSync('.private',{recursive:true});
const temp=mkdtempSync(resolve('.private/encryption-test-')),keyFile=join(temp,'keys.json');
const ring={active:'test1',keys:{test1:randomBytes(32).toString('base64')}};
writeFileSync(keyFile,JSON.stringify(ring),{mode:0o600});process.env.CARE24_KEY_FILE=keyFile;
test('AES-GCM uses fresh nonces, context binding and tamper detection',()=>{
 const plain='TEST-ONLY-ACCOUNT-9182',a=encryptText(plain,'care_contracts.bank_account'),b=encryptText(plain,'care_contracts.bank_account');
 assert.notEqual(a,b);assert.ok(!a.includes(plain));assert.equal(decryptText(a,'care_contracts.bank_account'),plain);
 assert.throws(()=>decryptText(a,'document_bundles.account_number'));
 const parts=a.split(':'),cipher=Buffer.from(parts.at(-1),'base64');cipher[0]^=1;parts[parts.length-1]=cipher.toString('base64');assert.throws(()=>decryptText(parts.join(':'),'care_contracts.bank_account'));
 assert.throws(()=>decryptText(plain,'care_contracts.bank_account'));
 const bytes=randomBytes(8192);assert.deepEqual(decryptBytes(encryptBytes(bytes,'upload:test'),'upload:test'),bytes);
 ring.keys.test2=randomBytes(32).toString('base64');ring.active='test2';writeFileSync(keyFile,JSON.stringify(ring));
 assert.equal(decryptText(a,'care_contracts.bank_account'),plain);assert.match(encryptText(plain,'test'),/^care24enc:v1:test2:/);
 const old=ring.keys.test1;ring.keys.test1=randomBytes(32).toString('base64');writeFileSync(keyFile,JSON.stringify(ring));assert.throws(()=>decryptText(a,'care_contracts.bank_account'));ring.keys.test1=old;writeFileSync(keyFile,JSON.stringify(ring));
 const saved=process.env.CARE24_KEY_FILE;delete process.env.CARE24_KEY_FILE;assert.throws(()=>encryptText(plain,'test'));process.env.CARE24_KEY_FILE=saved;
});
test('legacy DB and uploads migrate with verified encrypted backup and rerun safely',async()=>{
 const dbPath=join(temp,'fixture.db'),uploadDir=join(temp,'uploads'),url='file:'+dbPath.replaceAll('\\','/');
 const db=createClient({url});
 for(const[table,fields]of Object.entries(protectedFields))await db.execute(`CREATE TABLE ${table}(id INTEGER PRIMARY KEY,${fields.map(f=>f+" TEXT NOT NULL DEFAULT ''").join(',')})`);
 const marker='FIXTURE-RESIDENT-ONLY-88392';
 await db.execute({sql:'INSERT INTO document_bundles(id,account_number,criminal_request_data) VALUES(1,?,?)',args:[marker,JSON.stringify({subjectResidentNo:marker})]});db.close();
 const key='caregiver-documents/'+crypto.randomUUID();mkdirSync(join(uploadDir,'caregiver-documents'),{recursive:true});writeFileSync(join(uploadDir,key),marker);writeFileSync(join(uploadDir,key+'.json'),'{"contentType":"application/pdf"}');
 const script=resolve('scripts/encrypt-existing-data.mjs');
 const run=()=>{const r=spawnSync(process.execPath,[script],{cwd:temp,env:{...process.env,CARE24_DATABASE_URL:url,CARE24_UPLOAD_DIR:uploadDir},encoding:'utf8'});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout.trim());};
 const first=run();assert.equal(first.counts.document_bundles.converted,1);assert.equal(first.files,2);
 const converted=createClient({url});const row=(await converted.execute('SELECT * FROM document_bundles')).rows[0];assert.ok(row.account_number.startsWith(prefix));assert.equal(decryptText(row.account_number,'document_bundles.account_number'),marker);converted.close();
 assert.ok(!readFileSync(dbPath).includes(Buffer.from(marker)));assert.ok(!readFileSync(join(uploadDir,key)).includes(Buffer.from(marker)));assert.equal(decryptBytes(readFileSync(join(uploadDir,key)),'upload:'+key).toString(),marker);
 const snapshot=decryptBytes(readFileSync(join(first.backupDir,'database.enc')),'backup:database');const restore=join(temp,'restore.db');writeFileSync(restore,snapshot);const restored=createClient({url:'file:'+restore.replaceAll('\\','/')});assert.equal((await restored.execute('SELECT account_number FROM document_bundles')).rows[0].account_number,marker);restored.close();
 const second=run();assert.equal(second.counts.document_bundles.converted,0);assert.equal(second.files,0);
});
