import {withActor,scope,scopedId,ownership,workflowGuard,type Actor} from "../../../lib/auth";
import{desc,eq}from"drizzle-orm";import{getDb}from"../../../db";import{submissions}from"../../../db/schema";
const required=["caregiverName","caregiverOrg","contractType","feeType","feePeriod","satisfaction","overall","headNurse","confirmedAt"] as const;
function valid(b:Record<string,any>){const base=required.every(k=>String(b[k]||"").trim()),salary=b.contractType==="공동간병"?(b.commonFullTimeFee||b.commonTwoShiftFee||b.commonThreeShiftFee):b.personalFee;return base&&String(salary||"").trim()}
function values(b:Record<string,any>){const action=String(b.action||"save"),feeAmount=b.contractType==="개인간병"?b.personalFee:(b.commonFullTimeFee||b.commonTwoShiftFee||b.commonThreeShiftFee);return{caregiverName:b.caregiverName,caregiverOrg:b.caregiverOrg,caregiverHandwriting:b.caregiverHandwriting||"",ward:b.ward||"",room:b.room||"",patientName:b.patientName||"",workStart:b.workStart||"",workEnd:b.workEnd||"",contractType:b.contractType,feeType:b.feeType,feeAmount,feePeriod:b.feePeriod,commonFullTimeFee:b.commonFullTimeFee||"",commonTwoShiftFee:b.commonTwoShiftFee||"",commonThreeShiftFee:b.commonThreeShiftFee||"",personalFee:b.personalFee||"",feeNote:b.feeNote||"",satisfaction:b.satisfaction,duties:b.duties||"[]",rules:b.rules||"[]",overall:b.overall,headNurse:b.headNurse,confirmedAt:b.confirmedAt,status:action==="complete"?"completed":action==="confirm"?"confirmed":action==="send"?"sent":"saved",sentTargets:action==="save"?"":"간호사실 · 협회 · 간병24",completedAt:action==="complete"?new Date().toISOString():null}}
async function handleGET(req:Request, actor:Actor){try{return Response.json({submissions:await getDb().select().from(submissions).where(scope(submissions,actor)).orderBy(desc(submissions.id)).limit(100)})}catch{return Response.json({error:"약정서 접수함을 불러올 수 없습니다."},{status:500})}}
async function handlePOST(req:Request, actor:Actor){try{const b=await req.json() as Record<string,any>;if(!valid(b))return Response.json({error:"필수 약정서 항목을 모두 작성해주세요."},{status:400});const[x]=await getDb().insert(submissions).values({...values(b),...ownership(actor)}).returning();return Response.json({submission:x},{status:201})}catch{return Response.json({error:"약정서 저장 중 문제가 발생했습니다."},{status:500})}}
async function handlePATCH(req:Request, actor:Actor){try{const b=await req.json() as Record<string,any>,id=Number(b.id);if(!id||!valid(b))return Response.json({error:"필수 약정서 항목을 모두 작성해주세요."},{status:400});const[x]=await getDb().update(submissions).set(values(b)).where(scopedId(submissions,id,actor)).returning();return x?Response.json({submission:x}):Response.json({error:"약정서를 찾을 수 없습니다."},{status:404})}catch{return Response.json({error:"약정서 처리 중 문제가 발생했습니다."},{status:500})}}

export const GET=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handleGET(req,actor);});
export const POST=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePOST(req,actor);});
export const PATCH=(req:Request)=>withActor(req,async(actor)=>{await workflowGuard(req,actor);return handlePATCH(req,actor);});
